# pyright: strict
# Same strict-typing baseline as every psycopg example in this topic -- this
# capstone weaves together window functions, indexing, N+1, and locking, so it
# reuses the same type-checking discipline as every one of those individually.
"""Example 85: Capstone Preview, Tuning."""

# threading and Decimal together power Step 4's credit-limit race -- Decimal
# for exact money comparisons, threading for the genuine concurrency the race
# needs, exactly like Examples 26, 57-63, and 77-78 before it.
import threading
import time
from decimal import Decimal

# psycopg alone is enough -- no psycopg_pool needed here, unlike Example 76.
import psycopg

# Every step function below (setup, step1-4) shares this SAME connection
# string -- main() connects once and passes that one connection through.
DSN = "host=localhost port=55432 dbname=asqp user=asqp password=asqp"
# => connection string -- readers should substitute their own PostgreSQL 18 instance


# This capstone deliberately revisits FOUR separate concepts already taught in
# this topic (window functions, index tuning, N+1, row-locking races) inside
# ONE coherent order-book scenario, showing how they combine in practice.
def setup(conn: psycopg.Connection) -> None:  # => resets state -- fully self-contained
    """Seed a small order-book: customers with credit limits, and their orders."""
    # setup() uses a single cursor for its whole sequence of DDL and seed
    # INSERT statements, all committed together at the end.
    with conn.cursor() as cur:
        # Idempotent reset, same pattern used throughout this topic.
        cur.execute("SET client_min_messages TO WARNING")
        # Both tables dropped together -- cap_order references cap_customer,
        # so listing them in one statement avoids an FK-ordering headache.
        cur.execute("DROP TABLE IF EXISTS cap_order, cap_customer CASCADE")
        cur.execute(
            "CREATE TABLE cap_customer(id INTEGER PRIMARY KEY, name TEXT NOT NULL, "
            "credit_limit NUMERIC(10,2) NOT NULL)"
        )
        cur.execute(
            "CREATE TABLE cap_order(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "customer_id INTEGER NOT NULL REFERENCES cap_customer(id), order_date DATE NOT NULL, "
            "amount NUMERIC(10,2) NOT NULL)"
        )
        # => IDENTITY (not a manual MAX(id)+1 subquery) -- nextval() is ATOMIC under
        # => concurrency, avoiding a SEPARATE id-collision race in Step 4 below
        # Three customers, all with the SAME 1000.00 credit limit -- Step 4 only
        # needs Bob and Cara's rows to demonstrate the race; Alice's data exists
        # purely so Steps 1-3 have a genuinely multi-customer dataset to report on.
        cur.execute(
            "INSERT INTO cap_customer(id, name, credit_limit) VALUES "
            "(1, 'Alice', 1000.00), (2, 'Bob', 1000.00), (3, 'Cara', 1000.00)"
        )
        # Orders cycle round-robin across the 3 customers (1 + n % 3) and spread
        # across roughly 41 months of order_date -- enough volume and date range
        # for Step 1's window function and Step 2's index tuning to be meaningful.
        cur.execute(
            "INSERT INTO cap_order(id, customer_id, order_date, amount) "
            "SELECT n, 1 + (n % 3), DATE '2025-01-01' + ((n / 3) || ' days')::INTERVAL, "
            "(1 + (n % 5))::NUMERIC "
            "FROM generate_series(1, 45000) AS n"
        )
        # => 45,000 orders across 3 customers -- large enough that the report query's
        # => ORDER BY genuinely benefits from an index (co-23), unlike a toy-sized table
        cur.execute("SELECT setval(pg_get_serial_sequence('cap_order', 'id'), 45000)")
        # => advances the IDENTITY sequence PAST the 45,000 explicit ids just inserted,
        # => so Step 4's auto-generated ids never collide with the bulk-seeded ones
    conn.commit()


# Step 1 is the ANALYTICAL entry point into this capstone -- a running-total
# report is exactly the kind of query a real dashboard would run against this
# order-book schema, and it reuses the SAME window-function shape as Example 66.
def step1_window_report(conn: psycopg.Connection) -> None:
    # => STEP 1 (co-04): a running-total window report -- the analytical core of
    # => most operational dashboards, threading window functions into the workflow
    # Header prints separate each step's output visually when this script
    # runs end to end -- purely a console-readability aid.
    print("--- Step 1: Running-total window report ---")
    with conn.cursor() as cur:
        # PARTITION BY customer_id keeps each customer's running total independent
        # -- an explicit ROWS frame (like Example 66) makes it an accumulating sum,
        # not a RANGE-based peer-group total.
        cur.execute(
            "SELECT customer_id, order_date, amount, "
            "SUM(amount) OVER (PARTITION BY customer_id ORDER BY order_date "
            "ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_total "
            "FROM cap_order ORDER BY customer_id, order_date LIMIT 5"
        )
        # => LIMIT 5 only trims the DISPLAYED rows -- the window function still
        # => computes the running total over all 45,000 seeded rows underneath
        # row[3] is running_total -- indices 0-2 are customer_id, order_date,
        # and amount, matching the SELECT list's column order exactly.
        for row in cur.fetchall():
            print(f"  customer_id={row[0]} order_date={row[1]} running_total={row[3]}")
        # This trailing print makes clear the 5 displayed rows are a SAMPLE --
        # not the full extent of what the window function actually computed.
        print("  ... (45,000 rows total)")


# Step 2 takes Step 1's EXACT query and asks a different question: how well
# does it perform at scale, and can an index change its execution plan --
# directly reusing Example 41's Index Only Scan / EXPLAIN reasoning.
def step2_index_tuning(conn: psycopg.Connection) -> None:
    # => STEP 2 (co-23): the SAME report query, EXPLAINed before and after adding
    # => the composite index that makes its ORDER BY free instead of a Sort node
    # Same visual-separator convention as Step 1's header above.
    print("--- Step 2: Index tuning on the report query ---")
    # The SQL text is captured once in a variable and reused for both the BEFORE
    # and AFTER EXPLAIN calls -- guaranteeing the only difference between the two
    # runs is the presence of the new index, not any accidental query drift.
    report_sql = (
        "EXPLAIN SELECT customer_id, order_date, amount, "
        "SUM(amount) OVER (PARTITION BY customer_id ORDER BY order_date "
        "ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_total "
        "FROM cap_order ORDER BY customer_id, order_date"
    )
    with conn.cursor() as cur:
        # BEFORE: no supporting index exists yet -- expect a Sort node here.
        cur.execute(report_sql)
        # Each fetched row is a single line of EXPLAIN's plain-text plan output --
        # row[0] pulls the (only) text column out of each row.
        before_plan = [row[0] for row in cur.fetchall()]
        # A crude but effective textual check -- looking for the literal word
        # "Sort" in EXPLAIN's plan text is enough to detect an in-memory sort step.
        has_sort_before = any("Sort" in line for line in before_plan)
        print(f"  Before index -- plan has explicit Sort node: {has_sort_before}")

        # The composite index matches BOTH the PARTITION BY and ORDER BY columns
        # in the SAME order they appear in the window function -- this is what
        # lets the planner walk the index directly instead of sorting in memory.
        cur.execute(
            "CREATE INDEX idx_cap_order_customer_date ON cap_order(customer_id, order_date)"
        )
        # The index must be committed BEFORE the second EXPLAIN call below can
        # see and use it -- an uncommitted index is invisible to other queries.
        conn.commit()

        # This becomes a regular Index Scan, not an Index-Only Scan (co-19) --
        # the query also selects `amount`, which the composite index above does
        # not cover, so the planner still visits the heap for that column.
        # AFTER: the composite index now exists -- expect NO Sort node.
        cur.execute(report_sql)
        # Same list-comprehension extraction as before_plan above -- kept
        # symmetric so the two EXPLAIN outputs are compared identically.
        after_plan = [row[0] for row in cur.fetchall()]
        has_sort_after = any("Sort" in line for line in after_plan)
        # has_sort_before should be True, has_sort_after should be False --
        # that flip is the entire point of Step 2's demonstration.
        print(f"  After index -- plan has explicit Sort node: {has_sort_after}")


# Step 3 switches concepts entirely -- from ANALYTICAL query shape to a classic
# APPLICATION-layer performance bug: fetching related data in a loop instead of
# one JOIN, exactly the pattern from Examples 54 and 55.
def step3_n_plus_1_fix(conn: psycopg.Connection) -> None:
    # => STEP 3 (co-26): diagnose the N+1 pattern from fetching each customer's
    # => name SEPARATELY per order, then fix it with a single JOIN query
    # Same visual-separator convention as Steps 1 and 2.
    print("--- Step 3: N+1 diagnosis and fix ---")
    with conn.cursor() as outer:
        outer.execute("SELECT id, customer_id FROM cap_order ORDER BY id LIMIT 20")
        # => scoped to 20 orders for THIS diagnostic -- the N+1 problem's shape is
        # => identical at any scale; a small sample keeps the demo's output readable
        # A separate variable (not consumed inline) because the loop below
        # needs to iterate it twice conceptually: once to drive the naive
        # per-order lookups, and its length is implicit in naive_query_count.
        orders = outer.fetchall()
        # Starts at 1 to count the initial "fetch all orders" query itself,
        # before the per-order loop below adds one more for each iteration.
        naive_query_count = 1
        # Exactly Example 54's shape: ONE query for orders, then ONE MORE query
        # per order to fetch its customer's name -- 21 total queries for 20 orders.
        for _order_id, customer_id in orders:
            # A BRAND NEW cursor per iteration -- this is the N+1 pattern in
            # its purest form: one extra round trip for every single order.
            with conn.cursor() as inner:
                inner.execute(
                    "SELECT name FROM cap_customer WHERE id = %s", (customer_id,)
                )
                # Result discarded -- this diagnostic only counts queries, it
                # does not need to actually USE each customer's name.
                inner.fetchone()
                naive_query_count += 1
    print(f"  Naive per-order lookup: {naive_query_count} total queries")

    # The fix mirrors Example 55: ONE JOIN query replaces the entire loop above,
    # fetching every order's customer name in a single round trip.
    with conn.cursor() as cur:
        cur.execute(
            "SELECT o.id, c.name FROM cap_order o JOIN cap_customer c ON c.id = o.customer_id "
            "ORDER BY o.id"
        )
        # Result discarded here -- this call exists purely to prove the JOIN
        # query executes successfully and returns rows, not to display them.
        cur.fetchall()
    print("  JOIN fix: 1 total query")


# `amount` is typed Decimal, not float, throughout this capstone -- money
# arithmetic must avoid binary floating-point rounding error, and the
# 700.00 + 700.00 = 1400.00 comparison against a 1000.00 limit below needs
# to be an EXACT decimal comparison, not an approximately-correct one.
# This is the UNSAFE half of Step 4's race -- it deliberately omits the row
# lock that place_order_locked() below adds, reproducing the exact
# check-then-act race pattern from Example 26's "before" version.
def place_order_naive(customer_id: int, amount: Decimal, results: list[str]) -> None:
    # => the RACE (co-13): check credit, THEN insert -- with NO lock in between,
    # => two concurrent callers can both pass the check against the SAME stale total
    # A fresh connection per call -- exactly like Examples 26 and 60, this
    # models a genuinely separate client session, not a shared connection.
    conn = psycopg.connect(DSN)
    with conn.cursor() as cur:
        cur.execute("BEGIN")
        # A plain SELECT (no FOR UPDATE) takes NO row lock -- a second concurrent
        # thread's identical SELECT can run and read the SAME stale total, before
        # either thread's INSERT has been committed.
        cur.execute(
            "SELECT credit_limit, COALESCE((SELECT SUM(amount) FROM cap_order "
            "WHERE customer_id = %s), 0) FROM cap_customer WHERE id = %s",
            (customer_id, customer_id),
        )
        row = cur.fetchone()
        # Narrows Optional[Any] for the type checker -- COUNT-style
        # aggregate queries always return exactly one row.
        assert row is not None
        # Tuple unpacking assumes exactly 2 columns were selected, matching the
        # SELECT list's credit_limit, COALESCE(...) shape above.
        credit_limit, current_total = row
        # This check reads a SNAPSHOT total that a concurrent thread's INSERT
        # (not yet committed) will never be visible to under READ COMMITTED --
        # that invisibility is exactly what makes the race possible.
        if current_total + amount <= credit_limit:
            time.sleep(
                0.05
            )  # => widens the race window so the anomaly is reliably reproducible
            cur.execute(
                "INSERT INTO cap_order(customer_id, order_date, amount) "
                "VALUES (%s, CURRENT_DATE, %s)",
                (customer_id, amount),
            )
            conn.commit()
            # Only ONE of the two concurrent naive callers SHOULD pass this
            # check safely -- but both can, because neither sees the other's
            # pending (uncommitted) insert.
            results.append("placed")
        else:
            # A rollback here still counts as a full transaction -- the BEGIN
            # above must be closed one way or another before conn.close().
            conn.rollback()
            results.append("refused")
    # Closes regardless of whether this thread's order was placed or refused.
    conn.close()


# The FIXED counterpart to place_order_naive() above -- same overall shape
# (check credit, then insert), but FOR UPDATE closes the exact race window
# the naive version leaves open, directly reusing Example 26's lock pattern.
def place_order_locked(customer_id: int, amount: Decimal, results: list[str]) -> None:
    # => the FIX (co-13, co-16): SELECT ... FOR UPDATE locks the customer row FIRST
    # => -- a second concurrent caller genuinely BLOCKS until the first commits,
    # => so it re-checks against the UPDATED total, not a stale one
    # Same fresh-connection pattern as place_order_naive() above -- the ONLY
    # code difference between the two functions is the FOR UPDATE clause below.
    conn = psycopg.connect(DSN)
    with conn.cursor() as cur:
        cur.execute("BEGIN")
        # FOR UPDATE here is what makes the second concurrent call WAIT instead of
        # reading a stale value -- the entire fix lives in this one clause.
        cur.execute(
            "SELECT credit_limit FROM cap_customer WHERE id = %s FOR UPDATE",
            (customer_id,),
        )
        credit_row = cur.fetchone()
        assert credit_row is not None
        credit_limit = credit_row[0]
        # The running total is read SEPARATELY, but only AFTER the row lock above
        # is held -- any concurrent committer's rows are now guaranteed visible.
        cur.execute(
            "SELECT COALESCE(SUM(amount), 0) FROM cap_order WHERE customer_id = %s",
            (customer_id,),
        )
        # Two SEPARATE queries (credit_limit, then the SUM) rather than one
        # combined query like the naive version -- FOR UPDATE only applies to
        # the first SELECT, which is the one that needs the row lock.
        total_row = cur.fetchone()
        assert total_row is not None
        # total_row[0] is COALESCE(SUM(amount), 0) -- the single aggregate
        # column selected above.
        current_total = total_row[0]
        if current_total + amount <= credit_limit:
            cur.execute(
                "INSERT INTO cap_order(customer_id, order_date, amount) "
                "VALUES (%s, CURRENT_DATE, %s)",
                (customer_id, amount),
            )
            conn.commit()
            # Under the locked variant, the SECOND caller's re-read (after
            # waiting for FOR UPDATE) correctly reflects the FIRST caller's
            # now-committed order, making this check trustworthy.
            results.append("placed")
        else:
            # Correctly refuses -- this is the locked variant behaving as
            # designed, not a bug: the second order really would exceed the limit.
            conn.rollback()
            results.append("refused")
    # Same unconditional cleanup as place_order_naive() above.
    conn.close()


# Step 4 is the capstone's concurrency finale -- it runs BOTH place_order
# variants above against TWO different customers (Bob for naive, Cara for
# locked), so the contrast in results is directly attributable to the lock.
def step4_anomaly_resolution(conn: psycopg.Connection) -> None:
    # => STEP 4 (co-13): reproduce a credit-limit race under naive READ COMMITTED,
    # => then resolve it with the row-locking pattern from Example 26
    # Same visual-separator convention as every step before it.
    print("--- Step 4: Anomaly resolution (credit-limit race) ---")
    with conn.cursor() as cur:
        # => clear the bulk report-seed orders for Bob/Cara -- Step 1-3 needed
        # => volume, but the credit-limit race needs a CLEAN starting balance
        cur.execute("DELETE FROM cap_order WHERE customer_id IN (2, 3)")
        conn.commit()
        cur.execute(
            "SELECT COALESCE(SUM(amount), 0) FROM cap_order WHERE customer_id = 2"
        )
        row = cur.fetchone()
        # Narrows Optional[Any] for the type checker -- COUNT-style
        # aggregate queries always return exactly one row.
        assert row is not None
        # This baseline print confirms Bob starts the race at 0.00 -- the
        # DELETE above cleared every order-seed row for customers 2 and 3.
        print(f"  Bob's current total before race: {row[0]} (limit: 1000.00)")

    # Two concurrent 700.00 orders against Bob's 1000.00 limit -- EACH individually
    # passes the check (700 <= 1000), but together they would total 1400.00,
    # exceeding the limit if both are allowed to commit.
    # A shared list, appended to by both naive worker threads below.
    naive_results: list[str] = []
    # Plain list.append() from multiple threads is safe here without an explicit
    # Lock -- CPython's GIL makes each individual append() call atomic, and this
    # code never reads naive_results until after both threads have joined below.
    threads = [
        threading.Thread(
            target=place_order_naive, args=(2, Decimal("700.00"), naive_results)
        )
        for _ in range(2)
    ]
    # Two threads, both targeting customer_id=2 (Bob) with the identical
    # 700.00 amount -- maximizing the chance both race past the check.
    for t in threads:
        # Starting BOTH threads before joining either is what creates genuine
        # overlap -- sequential start-then-join-immediately would never race at all.
        t.start()
    for t in threads:
        # Waits for BOTH naive threads to fully finish before reading Bob's
        # post-race total below.
        t.join()
    print(f"  Naive (no lock): both concurrent 700.00 orders -> {naive_results}")

    with conn.cursor() as cur:
        cur.execute(
            "SELECT COALESCE(SUM(amount), 0) FROM cap_order WHERE customer_id = 2"
        )
        row = cur.fetchone()
        assert row is not None
        # If BOTH naive orders committed, this total will read 1400.00 --
        # visibly exceeding Bob's 1000.00 limit, proving the race occurred.
        print(f"  Bob's total after naive race: {row[0]} (limit was 1000.00)")

    # The SAME race, replayed against Cara using the LOCKED variant -- FOR UPDATE
    # forces the second thread to wait, re-read, and correctly refuse this time.
    # A shared list, appended to by both locked worker threads below.
    locked_results: list[str] = []
    threads2 = [
        threading.Thread(
            target=place_order_locked, args=(3, Decimal("700.00"), locked_results)
        )
        for _ in range(2)
    ]
    for t in threads2:
        # Same start-both-before-joining pattern as the naive race above.
        t.start()
    for t in threads2:
        # Waits for BOTH locked threads to finish before printing the final result.
        t.join()
    # Expect exactly one "placed" and one "refused" here -- unlike the naive
    # results above, which can show two "placed" entries under real contention.
    print(f"  Locked (FOR UPDATE): both concurrent 700.00 orders -> {locked_results}")


# main() threads all four steps together in sequence on ONE connection --
# window reporting, index tuning, N+1 diagnosis, and the concurrency fix --
# exactly the arc a real production tuning session would follow.
def main() -> None:  # => the script's entry point -- threads all 4 concepts together
    # main()'s single connection is reused across ALL FOUR steps -- Steps 1-4
    # run sequentially on ONE session, unlike Step 4's own worker functions,
    # which each open their own separate connections for genuine concurrency.
    conn = psycopg.connect(DSN)
    # Runs once, before any of the four steps below -- every step operates on
    # this same freshly-seeded order-book.
    setup(conn)
    # Step 1: analytical reporting.
    step1_window_report(conn)
    # Step 2: performance tuning on that same report query.
    step2_index_tuning(conn)
    # Step 3: an unrelated application-layer performance bug and its fix.
    step3_n_plus_1_fix(conn)
    # Step 4: a correctness bug (not just a performance one) and its fix.
    step4_anomaly_resolution(conn)
    conn.close()  # => always close what you open


# This capstone deliberately touches co-04, co-13, co-16, co-23, and co-26 --
# five separate concepts from across this topic's beginner, intermediate, and
# advanced examples, combined into one coherent, runnable scenario.
if __name__ == "__main__":  # => guards against running main() on `import example`
    main()  # => entry point -- runs everything above when executed as a script
