"""Example 27: pytest verification for Value Object: Immutable Money with Value Equality."""

import pytest  # => pytest.raises asserts a specific exception is raised

from example import Money


def test_equal_amounts_compare_equal_even_as_separate_objects() -> None:
    ten_usd: Money = Money(1000, "usd")
    same_value: Money = Money(1000, "usd")  # => a distinct object, identical field values
    assert ten_usd == same_value  # => value equality, generated by frozen=True
    assert ten_usd is not same_value  # => two genuinely different objects nonetheless


def test_money_is_immutable_after_construction() -> None:
    ten_usd: Money = Money(1000, "usd")
    with pytest.raises(AttributeError):  # => frozen=True raises rather than allowing mutation
        ten_usd.amount = 2000  # type: ignore  # => deliberately triggers the frozen guard this example teaches


# => Run: pytest -- Output: 2 passed
