-- Capstone: seed.sql -- schema + a dataset large enough for plans to differ.
-- Three tables model one coherent org: department (5 rows), employee (18 rows, a real
-- management hierarchy via manager_id, plus the on_call flag Step 4's anomaly needs), and
-- sales_event (250,000 rows) -- a fact table large enough that an index measurably changes
-- the planner's choice in overview.md Step 3 (co-01 through co-10's dataset-shape lessons,
-- applied here at capstone scale).
SET client_min_messages TO WARNING;

DROP TABLE IF EXISTS sales_event, employee, department CASCADE;
-- => resets state -- this seed is fully self-contained, safe to re-run

CREATE TABLE department (id INTEGER PRIMARY KEY, name TEXT NOT NULL);

CREATE TABLE employee (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  manager_id INTEGER REFERENCES employee (id),
  -- => self-referencing FK (co-03's shape): NULL only for the root (the CEO)
  department_id INTEGER NOT NULL REFERENCES department (id),
  salary NUMERIC(10, 2) NOT NULL,
  on_call BOOLEAN NOT NULL DEFAULT FALSE
  -- => only 2 Support employees start TRUE -- Step 4's write-skew invariant lives here
);

CREATE TABLE sales_event (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_ref TEXT NOT NULL,
  -- => a business-facing lookup key, deliberately left WITHOUT an index --
  -- overview.md Step 3 adds one and re-measures (co-18, co-24)
  employee_id INTEGER NOT NULL REFERENCES employee (id),
  sale_date DATE NOT NULL,
  amount NUMERIC(10, 2) NOT NULL
);

INSERT INTO
  department (id, name)
VALUES
  (1, 'Executive'),
  (2, 'Engineering'),
  (3, 'Sales'),
  (4, 'Support'),
  (5, 'Finance');

-- 18 employees, a real 4-level hierarchy under the CEO -- report.sql's recursive CTE
-- (co-03) walks this exact chain, and its window functions (co-04, co-05) partition by
-- department_id. Depths, by hand: Grace=0; the 4 VPs=1; Linus/Margaret=2; Donald/Frances/
-- Henry=3 -- report.sql's output is checked against these depths.
INSERT INTO
  employee (id, name, manager_id, department_id, salary, on_call)
VALUES
  (1, 'Grace (CEO)', NULL, 1, 250000.00, FALSE),
  (2, 'Ada (VP Engineering)', 1, 2, 190000.00, FALSE),
  (3, 'Alan (VP Sales)', 1, 3, 185000.00, FALSE),
  (4, 'Barbara (VP Support)', 1, 4, 175000.00, FALSE),
  (5, 'Carol (VP Finance)', 1, 5, 180000.00, FALSE),
  (6, 'Linus (Eng Lead)', 2, 2, 160000.00, FALSE),
  (7, 'Margaret (Eng Lead)', 2, 2, 155000.00, FALSE),
  (8, 'Donald (Engineer)', 6, 2, 130000.00, FALSE),
  (9, 'Frances (Engineer)', 6, 2, 128000.00, FALSE),
  (10, 'Henry (Engineer)', 7, 2, 125000.00, FALSE),
  (11, 'Irene (Sales Rep)', 3, 3, 95000.00, FALSE),
  (12, 'Jack (Sales Rep)', 3, 3, 98000.00, FALSE),
  (13, 'Karen (Sales Rep)', 3, 3, 92000.00, FALSE),
  (14, 'Leo (Support Eng)', 4, 4, 105000.00, TRUE),
  -- => on_call -- one of the 2 Step 4 starts with TRUE
  (15, 'Nancy (Support Eng)', 4, 4, 108000.00, TRUE),
  -- => on_call -- the other Step 4 starts with TRUE (invariant: at least 1 of these 2)
  (16, 'Oscar (Support Eng)', 4, 4, 102000.00, FALSE),
  (17, 'Paula (Finance Analyst)', 5, 5, 110000.00, FALSE),
  (18, 'Quinn (Finance Analyst)', 5, 5, 112000.00, FALSE);

-- 250,000 rows spread evenly across all 18 employees (~13,900 rows each) and 730 distinct
-- days -- large enough that Step 3's WHERE sale_ref = '...' lookup (matching exactly ONE
-- row out of 250,000) genuinely costs a full-table Seq Scan before an index exists.
INSERT INTO
  sales_event (sale_ref, employee_id, sale_date, amount)
SELECT
  'SALE-' || LPAD(n::TEXT, 9, '0'),
  1 + (n % 18),
  DATE '2024-01-01' + ((n % 730) || ' days')::INTERVAL,
  (10 + (n % 990))::NUMERIC
FROM
  generate_series(1, 250000) AS n;

ANALYZE department, employee, sales_event;
-- => co-25 -- fresh planner statistics, the honest starting point for overview.md Step 3
