# pyright: strict
"""Example 52: Reviewing an Autogenerated Migration -- a Rename Autogenerate Gets WRONG."""

from __future__ import annotations

import contextlib  # => co-20: swallows alembic's own non-deterministic scaffolding chatter, same reason as Example 48
import io  # => the throwaway buffer redirect_stdout writes that chatter INTO
import os  # => reads connection settings, and builds/removes the scratch project directory
import shutil  # => co-20: cleanup -- removes the scaffolded project directory once this example is done
import tempfile  # => co-20: a fresh, self-contained directory for the scaffolded migration project

from alembic import command  # => co-20: revision(autogenerate=True) is what DIFFS the models against the live schema
from alembic.config import Config  # => co-20: every alembic.command function needs one of these as its first argument
from sqlalchemy import create_engine, text  # => co-20: the live database autogenerate compares the models AGAINST
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column  # => co-20: the model this example's rename targets

SQLA_URL: str = os.environ.get(  # => the SQLAlchemy dialect+driver URL, distinct from a plain DB-API DSN
    "SQLA_URL", "postgresql+psycopg://postgres:postgres@localhost:5432/orm_by_example"
)  # => override SQLA_URL in the environment to point at a different Postgres instance


class Base(DeclarativeBase):  # => co-06: every mapped class in this program shares ONE DeclarativeBase
    pass  # => carries no columns -- purely a registry root


class Widget(Base):  # => co-20: the model's OWN column is `name` -- the live table below still calls it `old_name`
    __tablename__ = "widget"  # => the physical table name -- ALREADY exists, seeded with one row, before this runs
    id: Mapped[int] = mapped_column(primary_key=True)  # => auto-assigned by Postgres
    name: Mapped[str]  # => co-20: this is a RENAME from the live schema's `old_name`, not a brand-new column


ENV_PY = (  # => co-20: the SAME minimal env.py pattern from Example 51 -- built as separate, individually-commented lines
    "from alembic import context\n"  # => co-20: `context` is alembic's OWN migration-runtime handle
    "from sqlalchemy import engine_from_config, pool\n\n"  # => co-20: builds a real Engine straight from alembic.ini's own section
    "config = context.config\n"  # => co-20: the SAME Config object bootstrap() constructed, now read back inside env.py
    'target_metadata = config.attributes.get("target_metadata")\n\n\n'  # => co-20: set to Widget's own Base.metadata below
    "def run_migrations_online() -> None:\n"  # => co-20: THE function alembic's runtime calls for a live-connection migration
    "    connectable = engine_from_config(\n"  # => co-20: reads the sqlalchemy.* keys straight out of alembic.ini's own section
    '        config.get_section(config.config_ini_section, {}), prefix="sqlalchemy.", poolclass=pool.NullPool\n'  # => no reuse needed
    "    )\n"  # => a short-lived migration run has no reason to KEEP a pooled connection open afterward
    "    with connectable.connect() as connection:\n"  # => borrows ONE connection -- autogenerate reflects THROUGH it
    "        context.configure(connection=connection, target_metadata=target_metadata)\n"  # => co-20: what autogenerate DIFFS against
    "        with context.begin_transaction():\n"  # => co-20: wraps every upgrade()/downgrade() call in ONE transaction
    "            context.run_migrations()\n\n\n"  # => the actual dispatch -- also used by autogenerate's own reflection pass
    "run_migrations_online()\n"  # => co-20: executed the MOMENT alembic imports this file -- no __main__ guard, by design
)


def bootstrap(url: str, project_dir: str, metadata: object) -> Config:  # => co-20: metadata drives WHAT autogenerate compares to
    script_dir = os.path.join(project_dir, "migrations")  # => alembic's convention -- a "migrations" subfolder
    cfg = Config(os.path.join(project_dir, "alembic.ini"))  # => co-20: the Config object every command function needs
    cfg.set_main_option("script_location", script_dir)  # => tells Config where the scaffolded files live
    cfg.set_main_option("sqlalchemy.url", url)  # => co-20: the ONE connection string every migration runs against
    with contextlib.redirect_stdout(io.StringIO()):  # => swallows "Creating directory ... done" -- path varies per run
        command.init(cfg, script_dir)  # => co-20: scaffolds env.py, script.py.mako, README, versions/ (Example 48)
    with open(os.path.join(script_dir, "env.py"), "w") as f:  # => co-20: OVERWRITES the scaffolded env.py with our own
        f.write(ENV_PY)  # => a hand-edit step, exactly like a real project's post-init setup
    cfg.attributes["target_metadata"] = metadata  # => co-20: passed to env.py via `config.attributes`, alembic's own escape hatch
    return cfg  # => ready for command.revision(autogenerate=True)


if __name__ == "__main__":  # => module entry point -- only runs when executed directly, not on import
    engine = create_engine(SQLA_URL)  # => an ORM-capable engine, used to seed data AND verify the final corrected result
    with engine.begin() as conn:  # => begin(): auto-commits on a clean exit, auto-rolls-back on an exception
        conn.execute(text("DROP SCHEMA public CASCADE"))  # => wipes EVERY table -- fully isolated from other examples
        conn.execute(text("CREATE SCHEMA public"))  # => a blank public schema, about to get the PRE-rename table
        conn.execute(text("CREATE TABLE widget (id SERIAL PRIMARY KEY, old_name TEXT NOT NULL)"))  # => co-20: the OLD column name
        conn.execute(text("INSERT INTO widget (old_name) VALUES ('Widget1')"))  # => co-20: real data autogenerate must NOT lose

    project_dir = tempfile.mkdtemp(prefix="alembic_ex52_")  # => a fresh, throwaway migration project for this example
    cfg = bootstrap(SQLA_URL, project_dir, Base.metadata)  # => co-20: Widget's `name` column is what gets diffed against `old_name`

    with contextlib.redirect_stdout(io.StringIO()):  # => swallows "Generating ..." console chatter
        rev = command.revision(cfg, message="rename old_name to name", autogenerate=True, rev_id="0001")  # => co-20: THE naive diff
    assert rev is not None and not isinstance(rev, list)  # => narrows the Union return type for pyright --strict below
    naive_body = open(rev.path).read()  # => co-20: what autogenerate ACTUALLY proposed, read back from disk
    adds_name_column = "add_column" in naive_body and "'name'" in naive_body  # => co-20: proposes a brand-new `name` column
    print(f"naive diff drops old_name: {'drop_column' in naive_body and 'old_name' in naive_body}")
    print(f"naive diff adds name: {adds_name_column}")
    assert "drop_column" in naive_body and "add_column" in naive_body  # => Output: naive diff drops old_name: True
    # => Output: naive diff adds name: True
    # => co-20: autogenerate sees ONLY column names -- it has no idea `old_name` and `name` are the SAME data renamed;
    # => it proposes DROPPING `old_name` and ADDING a brand-new, nullable-then-NOT-NULL `name` -- applied as-is, this
    # => would SILENTLY DELETE every existing widget's value, which is exactly why "please adjust!" is not optional

    with open(rev.path, "w") as f:  # => co-20: THE HUMAN REVIEW STEP -- replaces the naive drop+add with a true rename
        f.write(  # => a hand-corrected migration that preserves the data autogenerate's proposal would have destroyed
            '"""rename old_name to name"""\n'  # => the migration's own docstring, unchanged from the autogenerated original
            "from typing import Sequence, Union\n"  # => typed to match what command.revision()'s own skeleton generates
            "from alembic import op\n\n"  # => co-20: `op.alter_column(..., new_column_name=...)` -- a TRUE rename, no data loss
            'revision: str = "0001"\n'  # => co-20: THIS revision's own id -- unchanged, still matches rev_id="0001"
            "down_revision: Union[str, Sequence[str], None] = None\n"  # => None -- this is the first revision in this project
            "branch_labels: Union[str, Sequence[str], None] = None\n"  # => unused here -- relevant only for branching histories
            "depends_on: Union[str, Sequence[str], None] = None\n\n"  # => unused here -- cross-branch dependency declarations
            "def upgrade() -> None:\n"  # => co-20: the CORRECTED forward direction -- rename in place, not drop-then-add
            '    op.alter_column("widget", "old_name", new_column_name="name")\n\n'  # => co-20: Postgres RENAMEs the column, keeps every value
            "def downgrade() -> None:\n"  # => the true inverse of the corrected rename above
            '    op.alter_column("widget", "name", new_column_name="old_name")\n'  # => renames back, again with no data loss
        )

    with contextlib.redirect_stdout(io.StringIO()):  # => swallows alembic's own noisy status lines
        command.upgrade(cfg, "head")  # => co-20: runs the CORRECTED migration, not the naive one
    with engine.begin() as conn:  # => a fresh connection to verify the FINAL, post-migration state
        names = conn.execute(text("SELECT name FROM widget")).scalars().all()  # => co-20: reads through the NEW column name
    print(f"names={names}")  # => Output: names=['Widget1']
    assert names == ["Widget1"]  # => co-20: the ORIGINAL value survived the rename -- the naive autogenerated version would have lost it
    # => this is a documented, permanent limitation of autogenerate, not a bug that a future alembic release will fix
    # => co-20: this is exactly why every autogenerated migration ships as a DRAFT for a human to review, never as a
    # => final answer -- autogenerate is excellent at spotting THAT something changed, unreliable at inferring WHY

    shutil.rmtree(project_dir)  # => cleanup -- this example's own throwaway project, not a real repository
    print("ex-52 OK")  # => Output: ex-52 OK
