# pyright: strict
"""Capstone Step 4: migration_and_bulk.py -- a reversible Alembic migration, then two bulk operations.

Assumes seed.py and relationships_and_n_plus_1.py already ran. Adds a real column to the LIVE shared
schema with a full upgrade/downgrade round trip (co-19, co-21), then closes with two set-based writes
(co-23): a 50-row bulk insert of new backlog tasks, and a bulk UPDATE that re-triages every 'open' task.
"""

from __future__ import annotations  # => enables modern type-hint syntax across this file

import contextlib  # => co-19: swallows alembic's own non-deterministic scaffolding chatter, same reason as Example 48
import io  # => the throwaway buffer redirect_stdout writes that chatter INTO
import os  # => reads connection settings, and builds/removes the scratch migration-project directory
import shutil  # => co-19: cleanup -- removes the scaffolded project directory once this step is done
import tempfile  # => co-19: a fresh, self-contained directory for the scaffolded migration project
from typing import Any  # => types SQLAlchemy's own untyped event-hook callback arguments

from alembic import command  # => co-19: init/revision/upgrade/downgrade -- the same API the alembic CLI itself calls
from alembic.config import Config  # => co-19: every alembic.command function needs one of these as its first argument
from sqlalchemy import MetaData, Table, create_engine, event, insert, text, update  # => co-23: insert()/update() build ONE bulk statement

SQLA_URL: str = os.environ.get(  # => the SQLAlchemy dialect+driver URL, distinct from a plain DB-API DSN
    "SQLA_URL",
    "postgresql+psycopg://postgres:postgres@localhost:5432/orm_by_example",  # => the fallback default
)  # => override SQLA_URL in the environment to point at a different Postgres instance

ENV_PY = (  # => co-19: the SAME minimal env.py pattern this topic's Alembic examples (48-54) all share
    "from alembic import context\n"  # => co-19: `context` is alembic's OWN migration-runtime handle
    "from sqlalchemy import engine_from_config, pool\n\n"  # => builds a real Engine straight from alembic.ini's own section
    "config = context.config\n"  # => co-19: the SAME Config object bootstrap() constructed, now read back inside env.py
    'target_metadata = config.attributes.get("target_metadata")\n\n\n'  # => None -- this migration is hand-written, not autogenerated
    "def run_migrations_online() -> None:\n"  # => co-19: THE function alembic's runtime calls for a live-connection migration
    "    connectable = engine_from_config(\n"  # => co-19: reads the sqlalchemy.* keys straight out of alembic.ini's own section
    '        config.get_section(config.config_ini_section, {}), prefix="sqlalchemy.", poolclass=pool.NullPool\n'  # => no reuse needed
    "    )\n"  # => a short-lived migration run has no reason to KEEP a pooled connection open afterward
    "    with connectable.connect() as connection:\n"  # => borrows ONE connection for the whole migration run
    "        context.configure(connection=connection, target_metadata=target_metadata)\n"  # => co-19: binds THIS run's connection
    "        with context.begin_transaction():\n"  # => co-19: wraps every upgrade()/downgrade() call in ONE transaction
    "            context.run_migrations()\n\n\n"  # => the actual dispatch -- calls upgrade()/downgrade() on the revision below
    "run_migrations_online()\n"  # => co-19: executed the MOMENT alembic imports this file -- no __main__ guard, by design
)  # => the fully assembled env.py source text, ready to be written out by bootstrap() below


def bootstrap(url: str, project_dir: str) -> Config:  # => co-19: init + env.py rewrite, shared setup for this step
    script_dir = os.path.join(project_dir, "migrations")  # => alembic's convention -- a "migrations" subfolder
    cfg = Config(os.path.join(project_dir, "alembic.ini"))  # => co-19: the Config object every command function needs
    cfg.set_main_option("script_location", script_dir)  # => tells Config where the scaffolded files live
    cfg.set_main_option("sqlalchemy.url", url)  # => co-19: the ONE connection string this migration runs against
    with contextlib.redirect_stdout(io.StringIO()):  # => swallows "Creating directory ... done" -- path varies per run
        command.init(cfg, script_dir)  # => co-19: scaffolds env.py, script.py.mako, README, versions/ (Example 48)
    with open(os.path.join(script_dir, "env.py"), "w") as f:  # => co-19: OVERWRITES the scaffolded env.py with our own
        f.write(ENV_PY)  # => a hand-edit step, exactly like a real project's post-init setup
    return cfg  # => ready for command.revision()/upgrade()/downgrade() calls


if __name__ == "__main__":  # => module entry point -- only runs when executed directly, not on import
    engine = create_engine(SQLA_URL)  # => an ORM-capable engine -- NOTE: no schema reset here, unlike every ex-NN example --
    # => this step deliberately runs against the LIVE team/member/task/assignment data seed.py and Step 3 already built

    # --- Step 4a: a reversible migration adding member.active (co-19, co-21) ---
    project_dir = tempfile.mkdtemp(prefix="alembic_capstone_")  # => a fresh, throwaway migration project for this step
    cfg = bootstrap(SQLA_URL, project_dir)  # => scaffolds + rewires env.py, matching Examples 48-54's own setup

    with contextlib.redirect_stdout(io.StringIO()):  # => swallows "Generating .../0001_add_member_active.py ... done"
        rev = command.revision(cfg, message="add member active flag", rev_id="0001")  # => co-19: an EMPTY skeleton, filled in below
    assert rev is not None and not isinstance(rev, list)  # => narrows the Union return type for pyright --strict below
    with open(rev.path, "w") as f:  # => co-19 + co-21: add-nullable, backfill, then tighten -- a REAL reversible round trip
        f.write(  # => overwrites the empty skeleton command.revision() scaffolded with real upgrade/downgrade logic
            '"""add member active flag"""\n'  # => the migration's own docstring
            "from typing import Sequence, Union\n"  # => typed to match what command.revision()'s own skeleton generates
            "from alembic import op\n"  # => co-19: `op.add_column`/`op.alter_column`/`op.drop_column` -- the schema edits
            "import sqlalchemy as sa\n\n"  # => the column TYPE for the new active column
            'revision: str = "0001"\n'  # => co-19: THIS revision's own id -- matches the rev_id passed to command.revision()
            "down_revision: Union[str, Sequence[str], None] = None\n"  # => None -- the first (and only) revision this step adds
            "branch_labels: Union[str, Sequence[str], None] = None\n"  # => unused here -- relevant only for branching histories
            "depends_on: Union[str, Sequence[str], None] = None\n\n"  # => unused here -- cross-branch dependency declarations
            "def upgrade() -> None:\n"  # => co-19: FORWARD -- adds active, backfills every EXISTING member to True, then tightens
            '    op.add_column("member", sa.Column("active", sa.Boolean(), nullable=True))\n'  # => nullable UNTIL backfilled
            "    conn = op.get_bind()\n"  # => co-19: op.get_bind() -- the LIVE connection this migration runs on
            '    conn.execute(sa.text("UPDATE member SET active = TRUE"))\n'  # => co-19: backfills every one of the 5 EXISTING rows
            '    op.alter_column("member", "active", nullable=False)\n\n'  # => co-19: NOW safe to require -- every row is backfilled
            "def downgrade() -> None:\n"  # => co-21: REVERSE -- drops the column, restoring the EXACT original member shape
            '    op.drop_column("member", "active")\n'  # => co-21: a true reversal -- no other column touched
        )  # => end of the revision file's full source text

    with contextlib.redirect_stdout(io.StringIO()):  # => swallows alembic's own noisy status lines
        command.upgrade(cfg, "head")  # => co-19: STEP 1 -- adds + backfills active for the 5 existing members
    with engine.begin() as conn:  # => a fresh connection to verify the UPGRADED state
        active_count = conn.execute(text("SELECT count(*) FROM member WHERE active = TRUE")).scalar_one()  # => reads the backfill
    print(f"after_upgrade_active_count={active_count}")  # => Output: after_upgrade_active_count=5
    assert active_count == 5  # => co-19: every one of the 5 pre-existing members was backfilled to active=TRUE, none skipped

    with contextlib.redirect_stdout(io.StringIO()):  # => swallows alembic's own noisy status lines
        command.downgrade(cfg, "base")  # => co-21: STEP 2 -- drops the column, undoing Step 1 completely
    with engine.begin() as conn:  # => a fresh connection to verify the column is truly GONE
        columns = conn.execute(  # => reads member's REAL columns straight from Postgres' own information_schema
            text("SELECT column_name FROM information_schema.columns WHERE table_name = 'member'")
        ).all()  # => a list of (column_name,) rows -- checked below for "active"'s absence
    has_active_after_down = "active" in {row[0] for row in columns}  # => co-21: confirms the rollback actually removed it
    print(f"has_active_after_downgrade={has_active_after_down}")  # => Output: has_active_after_downgrade=False
    assert has_active_after_down is False  # => co-21: member is back to its EXACT original shape -- id, name, team_id only
    shutil.rmtree(project_dir)  # => cleanup -- this step's own throwaway migration project, not a real repository

    # --- Step 4b: a 50-row bulk insert (co-23) -- ONE statement, not 50 round trips ---
    insert_statements: list[str] = []  # => every INSERT this step emits, captured for verification
    update_statements: list[str] = []  # => every UPDATE this step emits, captured for verification

    def on_execute(conn: Any, cursor: Any, statement: str, *rest: Any) -> None:  # => untyped hook params (SQLAlchemy's own)
        upper = statement.strip().upper()  # => normalizes once, checked against below
        if upper.startswith("INSERT INTO TASK"):  # => this hook only cares about task-table write traffic
            insert_statements.append(statement)  # => Step 4b's bulk insert should append exactly ONE entry here
        elif upper.startswith("UPDATE TASK"):  # => same table, the OTHER bulk write Step 4c below issues
            update_statements.append(statement)  # => Step 4c's bulk update should append exactly ONE entry here

    event.listens_for(engine, "before_cursor_execute")(on_execute)  # => attaches the hook to every statement on `engine`

    with engine.begin() as conn:  # => a plain Core connection -- no Session, no ORM objects involved at all
        backlog_rows = [{"title": f"Backlog Task {i}", "status": "open"} for i in range(1, 51)]  # => 50 plain dicts
        # => co-23: PyPika could build this same statement (co-03), but SQLAlchemy Core's own insert() is used here --
        # => the CHOICE between them is style, not capability; either tier avoids loading rows into Python objects
        metadata = MetaData()  # => co-23: a fresh, empty registry -- reflection below fills it in from the LIVE database,
        # => no declarative model needed just to bulk-write into a table that already exists on disk
        task_tbl = Table("task", metadata, autoload_with=conn)  # => co-23: reads task's REAL columns straight from Postgres
        conn.execute(insert(task_tbl), backlog_rows)  # => co-23: ONE Core insert(), executed with a LIST of 50 parameter sets
    with engine.begin() as conn:  # => a fresh connection, just to read back the final task count
        total_tasks = conn.execute(text("SELECT count(*) FROM task")).scalar_one()  # => confirms every row actually landed
    print(f"total_tasks_after_bulk_insert={total_tasks}")  # => Output: total_tasks_after_bulk_insert=55
    print(f"INSERT statements emitted: {len(insert_statements)}")  # => Output: INSERT statements emitted: 1
    assert total_tasks == 55  # => co-23: seed.py's original 5 tasks, plus all 50 backlog rows -- none dropped, none duplicated
    assert len(insert_statements) == 1  # => co-23: ONE statement, not 50 separate round trips

    # --- Step 4c: a set-based bulk UPDATE (co-23) -- re-triages EVERY 'open' task in one statement ---
    with engine.begin() as conn:  # => reuses the SAME reflected task_tbl -- no re-reflection needed for a second statement
        stmt = update(task_tbl).where(task_tbl.c.status == "open").values(status="triaged")  # => co-23: a SET-BASED expression
        # => matches BOTH seed.py's original open tasks (3 of the 5 non-done ones -- "Design onboarding flow" and
        # => "Write API docs" and "Plan Q3 roadmap") AND all 50 freshly bulk-inserted backlog rows, in ONE pass
        result = conn.execute(stmt)  # => co-23: Postgres reads AND writes every matching row server-side, in a single statement
        rows_matched = result.rowcount  # => the DRIVER's own count of rows this ONE statement actually touched
    with engine.begin() as conn:  # => a fresh connection, just to read back the final status breakdown
        triaged_count = conn.execute(text("SELECT count(*) FROM task WHERE status = 'triaged'")).scalar_one()  # => cross-check against rows_matched
    print(f"rows_matched_by_update={rows_matched} triaged_count={triaged_count}")  # => Output: rows_matched_by_update=53 triaged_count=53
    print(f"UPDATE statements emitted: {len(update_statements)}")  # => Output: UPDATE statements emitted: 1
    assert rows_matched == 53 and triaged_count == 53  # => co-23: 3 original open tasks + 50 backlog tasks, ALL re-triaged
    assert len(update_statements) == 1  # => co-23: ONE statement, not 53 separate per-row round trips
    # => co-23: a per-object ORM loop equivalent to Step 4b + 4c would have issued 50 INSERTs plus 53 UPDATEs -- 103
    # => round trips total, versus the 2 set-based statements this step actually sent; this is exactly the tradeoff
    # => co-25 names -- the ORM's per-object machinery (identity map, change tracking, cascades) earns its keep on
    # => CRUD and object-graph navigation (Step 3's whole point), and gets out of the way entirely for bulk writes like this
    print("migration_and_bulk.py OK")  # => Output: migration_and_bulk.py OK
