# pyright: strict
"""Example 78: Three Tiers + an N+1 Fix + a Migration -- End to End, in One Script."""

from __future__ import annotations

import contextlib  # => co-19: swallows alembic's own non-deterministic scaffolding chatter, same reason as Example 48
import io  # => the throwaway buffer redirect_stdout writes that chatter INTO
import os  # => reads connection settings, and builds/removes the scratch project directory
import shutil  # => co-19: cleanup -- removes the scaffolded project directory once this example is done
import tempfile  # => co-19: a fresh, self-contained directory for the scaffolded migration project
from collections.abc import Generator  # => the modern return-type annotation @contextmanager expects, not Iterator
from contextlib import contextmanager  # => co-15: a reusable "count queries in this block" helper, reused from Example 42
from typing import Any  # => types SQLAlchemy's own untyped event-hook callback arguments

import psycopg  # => co-01: tier 1 -- the raw DB-API driver, no builder or ORM involved
from alembic import command  # => co-19: init/revision/upgrade -- the same API the alembic CLI itself calls
from alembic.config import Config  # => co-19: every alembic.command function needs one of these as its first argument
import psycopg.sql  # => wraps a RUNTIME str as a Composable -- psycopg's stubs require this over a plain non-literal str
from pypika import Query, Table  # => co-01: tier 2 -- PyPika builds the SQL text, psycopg runs it
from pypika import functions as pypika_fn  # => co-03: PyPika's own COUNT() aggregate function, not a raw SQL fragment
from sqlalchemy import Engine, ForeignKey, create_engine, event, select, text  # => co-01: tier 3 -- the ORM's own select()
from sqlalchemy.orm import DeclarativeBase, Mapped, Session, mapped_column, relationship, selectinload  # => co-14: selectinload is the N+1 fix

PG_DSN: str = os.environ.get("PG_DSN", "postgresql://postgres:postgres@localhost:5432/orm_by_example")  # => a plain DB-API DSN
SQLA_URL: str = os.environ.get(  # => the SQLAlchemy dialect+driver URL, distinct from a plain DB-API DSN
    "SQLA_URL", "postgresql+psycopg://postgres:postgres@localhost:5432/orm_by_example"
)  # => override SQLA_URL in the environment to point at a different Postgres instance

ENV_PY = (  # => co-19: the SAME minimal env.py pattern from Examples 49-50 -- built as separate, individually-commented lines
    "from alembic import context\n"  # => co-19: `context` is alembic's OWN migration-runtime handle
    "from sqlalchemy import engine_from_config, pool\n\n"  # => co-19: builds a real Engine straight from alembic.ini's own section
    "config = context.config\n"  # => co-19: the SAME Config object bootstrap() constructed, now read back inside env.py
    'target_metadata = config.attributes.get("target_metadata")\n\n\n'  # => None -- this migration is hand-written, not autogenerated
    "def run_migrations_online() -> None:\n"  # => co-19: THE function alembic's runtime calls for a live-connection migration
    "    connectable = engine_from_config(\n"  # => co-19: reads the sqlalchemy.* keys straight out of alembic.ini's own section
    '        config.get_section(config.config_ini_section, {}), prefix="sqlalchemy.", poolclass=pool.NullPool\n'  # => no reuse needed
    "    )\n"  # => a short-lived migration run has no reason to KEEP a pooled connection open afterward
    "    with connectable.connect() as connection:\n"  # => borrows ONE connection for the whole migration run
    "        context.configure(connection=connection, target_metadata=target_metadata)\n"  # => co-19: binds THIS run's connection
    "        with context.begin_transaction():\n"  # => co-19: wraps every upgrade()/downgrade() call in ONE transaction
    "            context.run_migrations()\n\n\n"  # => the actual dispatch -- calls upgrade()/downgrade() on the revision below
    "run_migrations_online()\n"  # => co-19: executed the MOMENT alembic imports this file -- no __main__ guard, by design
)


class Base(DeclarativeBase):  # => co-06: every mapped class in this program shares ONE DeclarativeBase (tier 3)
    pass  # => carries no columns -- purely a registry root


class Customer(Base):  # => co-01: the SAME table all three tiers read, mapped only for tier 3
    __tablename__ = "customer"  # => the physical table name
    id: Mapped[int] = mapped_column(primary_key=True)  # => auto-assigned by Postgres
    name: Mapped[str]  # => a required TEXT column
    orders: Mapped[list[Order]] = relationship(back_populates="customer")  # => co-15: the relationship the N+1 fires through


class Order(Base):  # => co-01: the "many" side, joined against in ALL three tiers
    __tablename__ = "order_table"  # => named to avoid colliding with the SQL reserved word ORDER
    id: Mapped[int] = mapped_column(primary_key=True)  # => auto-assigned by Postgres
    customer_id: Mapped[int] = mapped_column(ForeignKey("customer.id"))  # => the FK column every tier's JOIN condition uses
    customer: Mapped[Customer] = relationship(back_populates="orders")  # => the reverse navigation, exercised in tier 3 below


def reset_and_seed(engine: Engine, n_customers: int) -> None:  # => shared setup -- fresh schema, N customers, one order each
    with engine.begin() as conn:  # => begin(): auto-commits on a clean exit, auto-rolls-back on an exception
        conn.execute(text("DROP SCHEMA public CASCADE"))  # => wipes EVERY table -- fully isolated from other examples
        conn.execute(text("CREATE SCHEMA public"))  # => a blank public schema to build both tables into
    Base.metadata.create_all(engine)  # => issues CREATE TABLE for both customer and order_table
    with Session(engine) as session:  # => a Session is the ORM's unit-of-work handle (co-12)
        for i in range(n_customers):  # => seeds N customers, one order each -- the SAME fixture data all three tiers read
            session.add(Customer(name=f"Customer{i}", orders=[Order()]))  # => a Customer plus exactly one child Order
        session.commit()  # => flushes all rows before any tier queries them


def tier1_raw_sql(dsn: str) -> list[tuple[str, int]]:  # => co-01 + co-02: raw parameterized SQL, manual row unpacking
    # => co-25: hand-written text, the SAME GROUP BY tier 2 and tier 3 below express in two OTHER ways
    sql = "SELECT c.name, COUNT(o.id) FROM customer c LEFT JOIN order_table o ON o.customer_id = c.id GROUP BY c.id, c.name ORDER BY c.name"
    with psycopg.connect(dsn) as conn, conn.cursor() as cur:  # => co-02: a plain DB-API connection, no builder or ORM at all
        cur.execute(sql)  # => co-25: a set-oriented GROUP BY, computed entirely server-side, in ONE round trip
        return [(name, count) for name, count in cur.fetchall()]  # => co-02: manual tuple unpacking into a typed list


def tier2_query_builder(dsn: str) -> list[tuple[str, int]]:  # => co-01 + co-03: PyPika composes the SAME query as data, not text
    customer_t, order_t = Table("customer"), Table("order_table")  # => co-03: bare table names -- no mapped class involved
    q = (
        Query.from_(customer_t)  # => co-03: the SAME GROUP BY as tier 1, built as a composable tree instead of a string
        .left_join(order_t)  # => co-03: the LEFT JOIN itself -- a method call, not string concatenation
        .on(order_t.customer_id == customer_t.id)  # => co-03: the JOIN condition, expressed as Field comparisons
        .groupby(customer_t.id, customer_t.name)  # => co-03: composed onto the SAME tree, one method at a time
        .orderby(customer_t.name)  # => matches tier 1's ORDER BY, so the two result lists compare equal below
        .select(customer_t.name, pypika_fn.Count(order_t.id))  # => co-03: PyPika's own COUNT() aggregate function
    )
    rendered = psycopg.sql.SQL(str(q))  # pyright: ignore[reportArgumentType]  # => wraps a runtime str -- Example 67's escape-hatch pattern
    with psycopg.connect(dsn) as conn, conn.cursor() as cur:  # => co-01: executed via the SAME raw DB-API as tier 1
        cur.execute(rendered)  # => co-01: PyPika BUILT the query, but a plain DB-API cursor still RUNS it
        return [(name, count) for name, count in cur.fetchall()]  # => co-03: identical shape to tier 1's return value


def tier3_orm(engine: Engine) -> list[tuple[str, int]]:  # => co-01 + co-06: the ORM tier -- object-shaped, in-Python aggregation
    with Session(engine) as session:  # => a Session is the ORM's unit-of-work handle (co-12)
        stmt = select(Customer).options(selectinload(Customer.orders))  # => co-14: the FIX -- eager-loads BEFORE the N+1 could fire
        customers = session.execute(stmt).scalars().all()  # => query #1 (parents) + query #2 (batched children) -- co-15's fix
        return sorted((c.name, len(c.orders)) for c in customers)  # => co-25: aggregation done in Python -- correct, but hand-rolled


@contextmanager  # => co-15: turns "count every SELECT fired inside this block" into a plain `with` statement
def query_counter(engine: Engine) -> Generator[list[int]]:  # => yields a one-element mutable box holding the running count
    box = [0]  # => a list, not a plain int -- the caller reads box[0] AFTER the block exits, still seeing live updates

    def on_execute(conn: Any, cursor: Any, statement: str, *rest: Any) -> None:  # => untyped hook params (SQLAlchemy's own)
        if statement.strip().upper().startswith("SELECT"):  # => this counter only cares about read traffic
            box[0] += 1  # => increments the SAME box the caller holds a reference to

    listener = event.listens_for(engine, "before_cursor_execute")(on_execute)  # => attaches for the block's duration
    try:  # => the caller's code runs HERE, between attach and detach
        yield box  # => hands the box to the `with` block -- readable both during and after
    finally:  # => detaches even if the caller's block raises
        event.remove(engine, "before_cursor_execute", listener)  # => cleanup -- the NEXT measurement starts at zero


def bootstrap_alembic(url: str, project_dir: str) -> Config:  # => co-19: init + env.py rewrite, shared setup for the migration step
    script_dir = os.path.join(project_dir, "migrations")  # => alembic's convention -- a "migrations" subfolder
    cfg = Config(os.path.join(project_dir, "alembic.ini"))  # => co-19: the Config object every command function needs
    cfg.set_main_option("script_location", script_dir)  # => tells Config where the scaffolded files live
    cfg.set_main_option("sqlalchemy.url", url)  # => co-19: the ONE connection string the migration runs against
    with contextlib.redirect_stdout(io.StringIO()):  # => swallows "Creating directory ... done" -- path varies per run
        command.init(cfg, script_dir)  # => co-19: scaffolds env.py, script.py.mako, README, versions/ (Example 48)
    with open(os.path.join(script_dir, "env.py"), "w") as f:  # => co-19: OVERWRITES the scaffolded env.py with our own
        f.write(ENV_PY)  # => a hand-edit step, exactly like a real project's post-init setup
    return cfg  # => ready for command.revision()/upgrade()/downgrade() calls


if __name__ == "__main__":  # => module entry point -- only runs when executed directly, not on import
    engine = create_engine(SQLA_URL)  # => an ORM-capable engine, shared by every tier and the migration step below
    reset_and_seed(engine, n_customers=3)  # => co-01: THE SAME fixture data all three tiers below independently read

    sql_result = tier1_raw_sql(PG_DSN)  # => co-01: tier 1 -- raw SQL
    builder_result = tier2_query_builder(PG_DSN)  # => co-01: tier 2 -- query builder
    orm_result = tier3_orm(engine)  # => co-01: tier 3 -- full ORM
    print(f"sql_result={sql_result}")  # => Output: sql_result=[('Customer0', 1), ('Customer1', 1), ('Customer2', 1)]
    assert sql_result == builder_result == orm_result  # => co-01: all three tiers agree on the IDENTICAL correct answer
    # => co-01: this is the SPECTRUM from Example 1, run for real -- three DIFFERENT code paths, one CORRECT answer

    with query_counter(engine) as before:  # => co-15: reproduces the N+1 -- NO eager-loading option this time
        with Session(engine) as session:  # => a FRESH session -- nothing cached
            for customer in session.execute(select(Customer)).scalars().all():  # => query #1
                _ = [o.id for o in customer.orders]  # => co-13: each access fires its OWN lazy round trip -- the N+1 itself
    with query_counter(engine) as after:  # => co-14: the SAME access pattern, now fixed with eager loading
        with Session(engine) as session:  # => a FRESH session -- nothing cached
            stmt = select(Customer).options(selectinload(Customer.orders))  # => co-14: the fix, identical to tier3_orm()
            for customer in session.execute(stmt).scalars().all():  # => query #1 (parents) + query #2 (batched children)
                _ = [o.id for o in customer.orders]  # => reads from memory -- zero additional round trips
    print(f"before={before[0]} after={after[0]}")  # => Output: before=4 after=2
    assert before[0] == 4 and after[0] == 2  # => co-15: N+1 (3 customers + 1 parent query) collapses to a CONSTANT 2
    # => co-15: this is Examples 36-37's fix, threaded through the SAME tier-3 code path tier3_orm() above already uses

    project_dir = tempfile.mkdtemp(prefix="alembic_ex78_")  # => a fresh, throwaway migration project for this example
    cfg = bootstrap_alembic(SQLA_URL, project_dir)  # => scaffolds + rewires env.py, matching the earlier Alembic examples
    with contextlib.redirect_stdout(io.StringIO()):  # => swallows "Generating .../0001_add_email.py ... done"
        rev = command.revision(cfg, message="add email", rev_id="0001")  # => co-19: an EMPTY skeleton, filled in below
    assert rev is not None and not isinstance(rev, list)  # => narrows the Union return type for pyright --strict below
    with open(rev.path, "w") as f:  # => co-19: a REVERSIBLE schema-only migration -- add a column, then drop it back
        f.write(  # => co-19: the SAME "built as separate, individually-commented string lines" pattern as Examples 49-54
            '"""add email"""\n'  # => the migration's own docstring
            "from typing import Sequence, Union\n"  # => typed to match what command.revision()'s own skeleton generates
            "from alembic import op\n"  # => co-19: `op.add_column`/`op.drop_column` -- the schema edits this migration makes
            "import sqlalchemy as sa\n\n"  # => the column TYPE for the new email column
            'revision: str = "0001"\n'  # => co-19: THIS revision's own id -- matches the rev_id passed to command.revision()
            "down_revision: Union[str, Sequence[str], None] = None\n"  # => None -- the first (and only) revision in this project
            "branch_labels: Union[str, Sequence[str], None] = None\n"  # => unused here -- relevant only for branching histories
            "depends_on: Union[str, Sequence[str], None] = None\n\n"  # => unused here -- cross-branch dependency declarations
            "def upgrade() -> None:\n"  # => co-19: FORWARD -- adds the column
            '    op.add_column("customer", sa.Column("email", sa.String, nullable=True))\n\n'  # => co-19: the additive half
            "def downgrade() -> None:\n"  # => co-19: REVERSE -- removes the SAME column, restoring the original shape
            '    op.drop_column("customer", "email")\n'  # => co-21: a TRUE reversal -- the schema round-trips exactly
        )
    with contextlib.redirect_stdout(io.StringIO()):  # => swallows alembic's own noisy status lines
        command.upgrade(cfg, "head")  # => co-19: runs the forward migration
    with engine.begin() as conn:  # => a fresh connection to verify the column now EXISTS
        after_up = conn.execute(text("SELECT column_name FROM information_schema.columns WHERE table_name = 'customer'")).all()
    with contextlib.redirect_stdout(io.StringIO()):  # => swallows alembic's own noisy status lines
        command.downgrade(cfg, "base")  # => co-19 + co-21: rolls the migration back
    with engine.begin() as conn:  # => a fresh connection to verify the column is now GONE again
        after_down = conn.execute(text("SELECT column_name FROM information_schema.columns WHERE table_name = 'customer'")).all()
    has_email_after_up = "email" in {row[0] for row in after_up}  # => co-19: confirms the forward step actually added the column
    has_email_after_down = "email" in {row[0] for row in after_down}  # => co-21: confirms the rollback actually removed it again

    # => co-19 + co-21: THIS is the "verify migrate-then-rollback returns the schema to its starting state" bar
    print(f"has_email_after_up={has_email_after_up}")  # => Output: has_email_after_up=True
    print(f"has_email_after_down={has_email_after_down}")  # => Output: has_email_after_down=False
    assert has_email_after_up is True  # => co-19: the migration applied cleanly
    assert has_email_after_down is False  # => co-21: the migration rolled back cleanly, restoring the original schema
    # => co-19: forward and rollback are BOTH exercised, not just the forward half -- an untested downgrade() is a liability
    # => co-01 + co-15 + co-19 + co-25: this IS the capstone's shape, in miniature -- the same domain queried through
    # => raw SQL, a query builder, and a full ORM (co-01), an N+1 reproduced then fixed with eager loading (co-15),
    # => and a schema change that both applies and rolls back correctly (co-19, co-21) -- every tier's trade-off
    # => demonstrated by running it, not asserted from memory; the full capstone develops this same shape further

    shutil.rmtree(project_dir)  # => cleanup -- this example's own throwaway project, not a real repository
    # => 78 examples, 27 concepts, one running theme -- pick the tier the WORKLOAD demands, not the tier you know best
    print("ex-78 OK")  # => Output: ex-78 OK
