# pyright: strict
"""Example 54: A drop-column Migration Whose downgrade() Explicitly REFUSES to Pretend."""

from __future__ import annotations

import contextlib  # => co-21: swallows alembic's own non-deterministic scaffolding chatter, same reason as Example 48
import io  # => the throwaway buffer redirect_stdout writes that chatter INTO
import os  # => reads connection settings, and builds/removes the scratch project directory
import shutil  # => co-21: cleanup -- removes the scaffolded project directory once this example is done
import tempfile  # => co-21: a fresh, self-contained directory for the scaffolded migration project

from alembic import command  # => co-21: init/revision/upgrade/downgrade -- the same API the alembic CLI itself calls
from alembic.config import Config  # => co-21: every alembic.command function needs one of these as its first argument
from alembic.script import ScriptDirectory  # => co-21: used to invoke downgrade() DIRECTLY, so this example can catch its error
from sqlalchemy import create_engine, text  # => co-21: confirms the dropped column's data is GONE after upgrade()

SQLA_URL: str = os.environ.get(  # => the SQLAlchemy dialect+driver URL, distinct from a plain DB-API DSN
    "SQLA_URL", "postgresql+psycopg://postgres:postgres@localhost:5432/orm_by_example"
)  # => override SQLA_URL in the environment to point at a different Postgres instance

ENV_PY = (  # => co-21: the SAME minimal env.py pattern from Examples 49-53 -- built as separate, individually-commented lines
    "from alembic import context\n"  # => co-21: `context` is alembic's OWN migration-runtime handle
    "from sqlalchemy import engine_from_config, pool\n\n"  # => co-21: builds a real Engine straight from alembic.ini's own section
    "config = context.config\n"  # => co-21: the SAME Config object bootstrap() constructed, now read back inside env.py
    'target_metadata = config.attributes.get("target_metadata")\n\n\n'  # => None -- this migration is hand-written, not autogenerated
    "def run_migrations_online() -> None:\n"  # => co-21: THE function alembic's runtime calls for a live-connection migration
    "    connectable = engine_from_config(\n"  # => co-21: reads the sqlalchemy.* keys straight out of alembic.ini's own section
    '        config.get_section(config.config_ini_section, {}), prefix="sqlalchemy.", poolclass=pool.NullPool\n'  # => no reuse needed
    "    )\n"  # => a short-lived migration run has no reason to KEEP a pooled connection open afterward
    "    with connectable.connect() as connection:\n"  # => borrows ONE connection for the whole migration run
    "        context.configure(connection=connection, target_metadata=target_metadata)\n"  # => co-21: binds THIS run's connection
    "        with context.begin_transaction():\n"  # => co-21: wraps every upgrade()/downgrade() call in ONE transaction
    "            context.run_migrations()\n\n\n"  # => the actual dispatch -- calls upgrade()/downgrade() on the revision below
    "run_migrations_online()\n"  # => co-21: executed the MOMENT alembic imports this file -- no __main__ guard, by design
)


def bootstrap(url: str, project_dir: str) -> Config:  # => co-21: init + env.py rewrite, shared setup for every Alembic example
    script_dir = os.path.join(project_dir, "migrations")  # => alembic's convention -- a "migrations" subfolder
    cfg = Config(os.path.join(project_dir, "alembic.ini"))  # => co-21: the Config object every command function needs
    cfg.set_main_option("script_location", script_dir)  # => tells Config where the scaffolded files live
    cfg.set_main_option("sqlalchemy.url", url)  # => co-21: the ONE connection string every migration runs against
    with contextlib.redirect_stdout(io.StringIO()):  # => swallows "Creating directory ... done" -- path varies per run
        command.init(cfg, script_dir)  # => co-21: scaffolds env.py, script.py.mako, README, versions/ (Example 48)
    with open(os.path.join(script_dir, "env.py"), "w") as f:  # => co-21: OVERWRITES the scaffolded env.py with our own
        f.write(ENV_PY)  # => a hand-edit step, exactly like a real project's post-init setup
    return cfg  # => ready for command.revision()/upgrade()/downgrade() calls


if __name__ == "__main__":  # => module entry point -- only runs when executed directly, not on import
    engine = create_engine(SQLA_URL)  # => an ORM-capable engine, used to seed data AND verify the post-upgrade state
    with engine.begin() as conn:  # => begin(): auto-commits on a clean exit, auto-rolls-back on an exception
        conn.execute(text("DROP SCHEMA public CASCADE"))  # => wipes EVERY table -- fully isolated from other examples
        conn.execute(text("CREATE SCHEMA public"))  # => a blank public schema, about to get the SOON-to-be-dropped column
        conn.execute(text("CREATE TABLE person (id SERIAL PRIMARY KEY, notes TEXT)"))  # => co-21: `notes` is what upgrade() drops
        conn.execute(text("INSERT INTO person (notes) VALUES ('irreplaceable free-text notes')"))  # => real data, about to be LOST

    project_dir = tempfile.mkdtemp(prefix="alembic_ex54_")  # => a fresh, throwaway migration project for this example
    # => contrast this with Example 53, where the data change WAS genuinely reversible and downgrade() proved it
    cfg = bootstrap(SQLA_URL, project_dir)  # => scaffolds + rewires env.py, matching the earlier Alembic examples' setup

    with contextlib.redirect_stdout(io.StringIO()):  # => swallows "Generating .../0001_drop_notes.py ... done"
        rev = command.revision(cfg, message="drop notes column", rev_id="0001")  # => co-21: an EMPTY skeleton, filled in below
    assert rev is not None and not isinstance(rev, list)  # => narrows the Union return type for pyright --strict below
    with open(rev.path, "w") as f:  # => co-21: upgrade() DROPS a column outright -- downgrade() cannot honestly restore it
        f.write(  # => the drop is real -- Postgres discards the column's data, no trace remains to reconstruct from
            '"""drop notes column, irreversibly"""\n'  # => the migration's own docstring, naming the trade-off up front
            "from typing import Sequence, Union\n"  # => typed to match what command.revision()'s own skeleton generates
            "from alembic import op\n\n"  # => co-21: `op.drop_column` -- the one-way schema edit this migration performs
            'revision: str = "0001"\n'  # => co-21: THIS revision's own id -- matches the rev_id passed to command.revision()
            "down_revision: Union[str, Sequence[str], None] = None\n"  # => None -- the first revision in this project
            "branch_labels: Union[str, Sequence[str], None] = None\n"  # => unused here -- relevant only for branching histories
            "depends_on: Union[str, Sequence[str], None] = None\n\n"  # => unused here -- cross-branch dependency declarations
            "def upgrade() -> None:\n"  # => co-21: FORWARD -- drops the column; its data is gone the moment this commits
            '    op.drop_column("person", "notes")\n\n'  # => co-21: Postgres discards `notes` for EVERY row, permanently
            "def downgrade() -> None:\n"  # => co-21: REVERSE -- explicitly REFUSES instead of silently pretending to undo it
            "    raise RuntimeError(\n"  # => co-21: a loud, immediate failure -- the honest alternative to a lying no-op downgrade
            '        "irreversible: dropped `person.notes` data cannot be reconstructed -- restore from a backup instead"\n'
            "    )\n"  # => co-21: this message is what an operator SEES if they ever try `alembic downgrade -1` on this revision
        )

    with contextlib.redirect_stdout(io.StringIO()):  # => swallows alembic's own noisy status lines
        command.upgrade(cfg, "head")  # => co-21: runs upgrade() -- `notes` and its data are now genuinely gone
    with engine.begin() as conn:  # => a fresh connection to confirm the column is gone at the DATABASE level, not just in the file
        columns = conn.execute(text("SELECT column_name FROM information_schema.columns WHERE table_name = 'person'"))
        column_names = sorted(row[0] for row in columns)  # => co-21: reads Postgres' OWN catalog, not the migration's own claim
    print(f"columns after upgrade: {column_names}")  # => Output: columns after upgrade: ['id']
    assert column_names == ["id"]  # => co-21: `notes` is truly gone -- there is nothing left for a downgrade to restore
    # => no UPDATE ever copied `notes` anywhere first -- this is what makes the drop genuinely irreversible, not a choice

    script = ScriptDirectory.from_config(cfg)  # => co-21: reads the revision GRAPH so this example can call downgrade() directly
    revision_obj = script.get_revision("0001")  # => co-21: the loaded revision object -- its module holds the downgrade() function
    # => a real `alembic downgrade -1` invocation would load and call this SAME module function, the identical guard fires
    assert revision_obj is not None and revision_obj.module is not None  # => narrows Optional[...] for pyright --strict below
    try:  # => co-21: calling downgrade() directly -- exactly what alembic's own runtime would invoke on a real rollback attempt
        revision_obj.module.downgrade()  # => co-21: THE guard -- raises instead of returning silently
        raise AssertionError("expected RuntimeError")  # => fails loudly if the guard was ever accidentally removed
    except RuntimeError as exc:  # => co-21: the exact, deliberate failure this migration's author wrote
        print(f"downgrade raised: {exc}")  # => Output: downgrade raised: irreversible: dropped `person.notes` data cannot be reconstructed -- restore from a backup instead
        # => an operator reading this message knows EXACTLY what to do next -- a bare `pass` would have told them nothing
    # => co-21: a downgrade() that just `pass`es for an unrecoverable change is WORSE than no downgrade at all -- it tells
    # => an operator "rollback succeeded" while quietly leaving the schema wrong; raising here converts a silent lie
    # => into a loud, honest signal that says exactly what to do instead (restore from backup, not retry the rollback)

    shutil.rmtree(project_dir)  # => cleanup -- this example's own throwaway project, not a real repository
    print("ex-54 OK")  # => Output: ex-54 OK
