# pyright: strict
"""Example 76: Expand-Contract -- an ADDITIVE Step the Old App Survives, Then a Cleanup Step."""

from __future__ import annotations

import contextlib  # => co-21: swallows alembic's own non-deterministic scaffolding chatter, same reason as Example 48
import io  # => the throwaway buffer redirect_stdout writes that chatter INTO
import os  # => reads connection settings, and builds/removes the scratch project directory
import shutil  # => co-21: cleanup -- removes the scaffolded project directory once this example is done
import tempfile  # => co-21: a fresh, self-contained directory for the scaffolded migration project

from alembic import command  # => co-21: init/revision/upgrade -- the same API the alembic CLI itself calls
from alembic.config import Config  # => co-21: every alembic.command function needs one of these as its first argument
from sqlalchemy import create_engine, text  # => co-21: reads ACTUAL column values back at each stage of the rollout
# => co-19 + co-21: TWO migrations, chained by down_revision -- expand (0001) then contract (0002), never one big rename

SQLA_URL: str = os.environ.get(  # => the SQLAlchemy dialect+driver URL, distinct from a plain DB-API DSN
    "SQLA_URL", "postgresql+psycopg://postgres:postgres@localhost:5432/orm_by_example"
)  # => override SQLA_URL in the environment to point at a different Postgres instance

ENV_PY = (  # => co-21: the SAME minimal env.py pattern from Examples 49-50 -- built as separate, individually-commented lines
    "from alembic import context\n"  # => co-21: `context` is alembic's OWN migration-runtime handle
    "from sqlalchemy import engine_from_config, pool\n\n"  # => co-21: builds a real Engine straight from alembic.ini's own section
    "config = context.config\n"  # => co-21: the SAME Config object bootstrap() constructed, now read back inside env.py
    'target_metadata = config.attributes.get("target_metadata")\n\n\n'  # => None -- these migrations are hand-written, not autogenerated
    "def run_migrations_online() -> None:\n"  # => co-21: THE function alembic's runtime calls for a live-connection migration
    "    connectable = engine_from_config(\n"  # => co-21: reads the sqlalchemy.* keys straight out of alembic.ini's own section
    '        config.get_section(config.config_ini_section, {}), prefix="sqlalchemy.", poolclass=pool.NullPool\n'  # => no reuse needed
    "    )\n"  # => a short-lived migration run has no reason to KEEP a pooled connection open afterward
    "    with connectable.connect() as connection:\n"  # => borrows ONE connection for the whole migration run
    "        context.configure(connection=connection, target_metadata=target_metadata)\n"  # => co-21: binds THIS run's connection
    "        with context.begin_transaction():\n"  # => co-21: wraps every upgrade() call in ONE transaction
    "            context.run_migrations()\n\n\n"  # => the actual dispatch -- calls upgrade() on whichever revision is targeted
    "run_migrations_online()\n"  # => co-21: executed the MOMENT alembic imports this file -- no __main__ guard, by design
)


def bootstrap(url: str, project_dir: str) -> Config:  # => co-21: init + env.py rewrite, shared setup for every Alembic example
    script_dir = os.path.join(project_dir, "migrations")  # => alembic's convention -- a "migrations" subfolder
    cfg = Config(os.path.join(project_dir, "alembic.ini"))  # => co-21: the Config object every command function needs
    cfg.set_main_option("script_location", script_dir)  # => tells Config where the scaffolded files live
    cfg.set_main_option("sqlalchemy.url", url)  # => co-21: the ONE connection string every migration runs against
    with contextlib.redirect_stdout(io.StringIO()):  # => swallows "Creating directory ... done" -- path varies per run
        command.init(cfg, script_dir)  # => co-21: scaffolds env.py, script.py.mako, README, versions/ (Example 48)
    with open(os.path.join(script_dir, "env.py"), "w") as f:  # => co-21: OVERWRITES the scaffolded env.py with our own
        f.write(ENV_PY)  # => a hand-edit step, exactly like a real project's post-init setup
    return cfg  # => ready for command.revision()/upgrade() calls


if __name__ == "__main__":  # => module entry point -- only runs when executed directly, not on import
    engine = create_engine(SQLA_URL)  # => an ORM-capable engine, used to seed data AND verify each stage of the rollout
    with engine.begin() as conn:  # => begin(): auto-commits on a clean exit, auto-rolls-back on an exception
        conn.execute(text("DROP SCHEMA public CASCADE"))  # => wipes EVERY table -- fully isolated from other examples
        conn.execute(text("CREATE SCHEMA public"))  # => a blank public schema, about to get the PRE-rename table
        conn.execute(text("CREATE TABLE person (id SERIAL PRIMARY KEY, email TEXT NOT NULL)"))  # => co-21: the OLD column name
        conn.execute(text("INSERT INTO person (email) VALUES ('ada@example.com')"))  # => co-21: real data both steps must preserve

    project_dir = tempfile.mkdtemp(prefix="alembic_ex76_")  # => a fresh, throwaway migration project for this example
    cfg = bootstrap(SQLA_URL, project_dir)  # => scaffolds + rewires env.py, matching the earlier Alembic examples' setup

    with contextlib.redirect_stdout(io.StringIO()):  # => swallows "Generating .../0001_expand.py ... done"
        expand_rev = command.revision(cfg, message="expand: add contact_email", rev_id="0001")  # => co-21: STEP 1's skeleton
    assert expand_rev is not None and not isinstance(expand_rev, list)  # => narrows the Union return type for pyright --strict below
    with open(expand_rev.path, "w") as f:  # => co-21: EXPAND -- purely ADDITIVE, so a still-running old app instance keeps working
        f.write(  # => adds contact_email and backfills it, but leaves `email` untouched -- nothing old code depends on breaks
            '"""expand: add contact_email"""\n'  # => the migration's own docstring
            "from typing import Sequence, Union\n"  # => typed to match what command.revision()'s own skeleton generates
            "from alembic import op\n"  # => co-21: `op.add_column` -- the schema edit this step makes
            "import sqlalchemy as sa\n\n"  # => the column TYPE for the new contact_email column
            'revision: str = "0001"\n'  # => co-21: THIS revision's own id -- matches the rev_id passed to command.revision()
            "down_revision: Union[str, Sequence[str], None] = None\n"  # => None -- the first revision in this project
            "branch_labels: Union[str, Sequence[str], None] = None\n"  # => unused here -- relevant only for branching histories
            "depends_on: Union[str, Sequence[str], None] = None\n\n"  # => unused here -- cross-branch dependency declarations
            "def upgrade() -> None:\n"  # => co-21 + co-19: ADD then BACKFILL, never remove -- the additive half of the pattern
            '    op.add_column("person", sa.Column("contact_email", sa.String, nullable=True))\n'  # => nullable UNTIL backfilled
            "    conn = op.get_bind()\n"  # => co-21: op.get_bind() -- the LIVE connection this migration runs on, for row-level SQL
            '    conn.execute(sa.text("UPDATE person SET contact_email = email"))\n'  # => co-21: copies every existing row's value across
            '    op.alter_column("person", "contact_email", nullable=False)\n'  # => co-21: NOW safe to require -- every row is backfilled
            "    pass\n"  # => co-21: `email` is DELIBERATELY untouched here -- the contract step, not this one, removes it
        )

    with contextlib.redirect_stdout(io.StringIO()):  # => swallows alembic's own noisy status lines
        command.upgrade(cfg, "head")  # => co-21 + co-19: runs the EXPAND step -- migration 1 of 2
    with engine.begin() as conn:  # => a fresh connection to verify BOTH columns work at this midpoint
        old_col = conn.execute(text("SELECT email FROM person")).scalar_one()  # => co-21: the OLD app path -- still readable
        new_col = conn.execute(text("SELECT contact_email FROM person")).scalar_one()  # => co-21: the NEW app path -- already readable
    # => co-19: THIS is the "verify the additive step" half of the pattern -- both column names resolve to the same value
    print(f"after expand: email={old_col!r} contact_email={new_col!r}")  # => Output: after expand: email='ada@example.com' contact_email='ada@example.com'
    assert old_col == new_col == "ada@example.com"  # => co-19 + co-21: an OLD deploy AND a NEW deploy can BOTH run against this schema

    with contextlib.redirect_stdout(io.StringIO()):  # => swallows "Generating .../0002_contract.py ... done"
        contract_rev = command.revision(cfg, message="contract: drop email", rev_id="0002")  # => co-21: STEP 2's skeleton
    assert contract_rev is not None and not isinstance(contract_rev, list)  # => narrows the Union return type for pyright --strict below
    with open(contract_rev.path, "w") as f:  # => co-21: CONTRACT -- runs ONLY after every app instance has cut over to contact_email
        f.write(  # => the cleanup half -- drops the now-unused `email` column, completing the rename without a hard cutover
            '"""contract: drop email"""\n'  # => the migration's own docstring
            "from typing import Sequence, Union\n"  # => typed to match what command.revision()'s own skeleton generates
            "from alembic import op\n\n"  # => co-21: `op.drop_column` -- the schema edit this step makes
            'revision: str = "0002"\n'  # => co-21: THIS revision's own id -- matches the rev_id passed to command.revision()
            'down_revision: Union[str, Sequence[str], None] = "0001"\n'  # => co-19: chains AFTER the expand step -- ordering matters
            "branch_labels: Union[str, Sequence[str], None] = None\n"  # => unused here -- relevant only for branching histories
            "depends_on: Union[str, Sequence[str], None] = None\n\n"  # => unused here -- cross-branch dependency declarations
            "def upgrade() -> None:\n"  # => co-21 + co-19: the CONTRACT half -- only safe once every reader has moved off `email`
            '    op.drop_column("person", "email")\n'  # => co-21: removes the OLD column -- the rename is now truly complete
        )

    with contextlib.redirect_stdout(io.StringIO()):  # => swallows alembic's own noisy status lines
        command.upgrade(cfg, "head")  # => co-21 + co-19: runs the CONTRACT step -- migration 2 of 2, the cleanup
    with engine.begin() as conn:  # => a fresh connection to verify the FINAL, post-cleanup shape
        # => co-21: reads Postgres' OWN catalog table (information_schema), not application code -- the ground truth for the schema
        columns = sorted(row[0] for row in conn.execute(text("SELECT column_name FROM information_schema.columns WHERE table_name = 'person'")))
    print(f"after contract: columns={columns}")  # => Output: after contract: columns=['contact_email', 'id']
    assert columns == ["contact_email", "id"]  # => co-21: `email` is GONE -- the two-step rollout finished with zero all-at-once cutover
    # => co-19 + co-21: at NO point did a currently-running application break -- the expand step was purely additive
    # => (any old deploy still reading `email` kept working), and the contract step ran only AFTER every deploy had
    # => cut over to `contact_email`; a single one-shot "rename column" migration would have broken whichever app
    # => version was mid-deploy the moment it ran -- expand-contract trades one migration for two, buying zero downtime

    shutil.rmtree(project_dir)  # => cleanup -- this example's own throwaway project, not a real repository
    print("ex-76 OK")  # => Output: ex-76 OK
