//! Codex platform binding converter — `.claude/agents/` → `.codex/agents/`.
//!
//! Emits one standalone TOML file per Claude agent, carrying exactly `name`,
//! `description`, and `developer_instructions` in that fixed order. Every other
//! Claude frontmatter field is dropped, most of them with a conversion warning:
//! `model`, `model_reasoning_effort`, `sandbox_mode`, and `mcp_servers` have no
//! verified Claude-to-Codex translation, and omitting a field lets Codex apply
//! its own default rather than pinning an invented one.
//!
//! Structured as the sibling of [`super::converter`]: a field-policy table, a
//! fixed emitted-field order, and an encoder — with a TOML encoder in place of
//! the `OpenCode` YAML-frontmatter one.

use std::collections::HashMap;
use std::fmt::Write as FmtWrite;
use std::fs;
use std::path::Path;
use std::sync::OnceLock;

use serde_norway::Value;

use super::converter::{
    ConversionWarning, ConvertAllResult, discover_agent_sources, rebase_agent_links,
};
use super::field_policy::{FieldAction, FieldPolicy, walk_frontmatter_fields};
use super::frontmatter::extract_frontmatter;

/// Relative path of the Codex agent directory.
pub const CODEX_AGENT_DIR: &str = ".codex/agents";

/// The only file extension Codex CLI recognises for a standalone agent file
/// under [`CODEX_AGENT_DIR`].
///
/// Codex reads TOML there, never Markdown — a `.md` file in that directory is
/// silently ignored, which is why the bindings validator rejects one outright
/// rather than warning.
pub const CODEX_AGENT_EXTENSION: &str = "toml";

/// Relative path of the Codex configuration file, part of which this emitter
/// owns (see [`rewrite_generated_region`]).
pub const CODEX_CONFIG_FILE: &str = ".codex/config.toml";

/// Opening delimiter of the region of [`CODEX_CONFIG_FILE`] this emitter owns.
pub const GENERATED_REGION_START: &str =
    "# >>> rhino-cli generated: codex agents - do not edit inside this region";

/// Closing delimiter of the generated region.
///
/// **Marker-first hazard**: [`rewrite_generated_region`] looks for THIS marker
/// before it looks for any insertion anchor. An anchor-first implementation
/// finds the anchor on every run and appends a fresh region each time, so the
/// file grows a duplicate block per invocation and the idempotence gate fails.
/// The end marker is the only reliable "already applied" signal.
pub const GENERATED_REGION_END: &str = "# <<< rhino-cli generated: codex agents";

/// Remediation sentence shared by Codex mirror drift checks.
pub const CODEX_MIRROR_REMEDIATION: &str =
    "run `rhino-cli harness bindings generate` to regenerate the Codex mirror";

/// Fixed key order emitted by [`encode_codex_agent`]. The order is part of the
/// generated bytes the parity guard compares, so it is declared once here
/// rather than implied by struct field order.
const CODEX_EMITTED_FIELDS: &[&str] = &["name", "description", "developer_instructions"];

/// Static (field, action, reason) table powering [`codex_field_policy`].
///
/// Everything except `name` and `description` is dropped. The `DropWarn`
/// entries are the fields a reader might reasonably expect to survive; the
/// warning is what tells them it did not, and why.
pub const CODEX_FIELD_POLICY_TABLE: &[(&str, FieldAction, &str)] = &[
    ("name", FieldAction::Preserve, ""),
    ("description", FieldAction::Preserve, ""),
    (
        "model",
        FieldAction::DropWarn,
        "no verified claude-to-codex model mapping; codex applies its own default",
    ),
    (
        "color",
        FieldAction::DropWarn,
        "codex agent files declare no color",
    ),
    (
        "tools",
        FieldAction::DropWarn,
        "codex governs tool access through sandbox and approval policy, not per agent",
    ),
    (
        "skills",
        FieldAction::DropWarn,
        "codex discovers skills from .agents/skills, not from an agent file",
    ),
    ("maxTurns", FieldAction::DropWarn, "no codex equivalent"),
    (
        "disallowedTools",
        FieldAction::DropWarn,
        "no codex equivalent",
    ),
    (
        "permissionMode",
        FieldAction::DropWarn,
        "codex declares sandbox_mode at config level",
    ),
    ("effort", FieldAction::DropWarn, "claude-only"),
    ("memory", FieldAction::DropWarn, "claude-only"),
    ("isolation", FieldAction::DropWarn, "claude-only"),
    ("background", FieldAction::DropWarn, "claude-only"),
    ("initialPrompt", FieldAction::DropWarn, "claude-only"),
    (
        "mcpServers",
        FieldAction::DropWarn,
        "codex declares mcp_servers at config level",
    ),
    ("hooks", FieldAction::DropWarn, "no codex equivalent"),
];

/// Codex agent emit shape: `name`, `description`, `developer_instructions`.
#[derive(Debug, Clone, Default)]
pub struct CodexAgent {
    /// Agent name (always emitted).
    pub name: String,
    /// Agent description (always emitted).
    pub description: String,
    /// The Claude agent body, carried verbatim (always emitted).
    pub developer_instructions: String,
}

/// One generated agent as the `.codex/config.toml` region needs it.
#[derive(Debug, Clone)]
pub struct EmittedCodexAgent {
    /// Agent name — the `[agents.<name>]` table key.
    pub name: String,
    /// Agent description, mirrored from the Claude source.
    pub description: String,
}

/// Everything one Codex emit run produced.
#[derive(Debug, Default)]
pub struct CodexEmitResult {
    /// Per-file conversion tallies and warnings.
    pub result: ConvertAllResult,
    /// The agents that were emitted, in `name` order.
    pub agents: Vec<EmittedCodexAgent>,
}

/// Return the lazily-initialized Codex field policy map.
fn codex_field_policy() -> &'static HashMap<&'static str, FieldPolicy> {
    static M: OnceLock<HashMap<&'static str, FieldPolicy>> = OnceLock::new();
    M.get_or_init(|| {
        CODEX_FIELD_POLICY_TABLE
            .iter()
            .map(|(k, action, reason)| {
                (
                    *k,
                    FieldPolicy {
                        action: *action,
                        reason,
                    },
                )
            })
            .collect()
    })
}

/// Return true when `file_name` is NOT a file Codex CLI would read as a
/// standalone agent definition under [`CODEX_AGENT_DIR`] — anything that is not
/// a `.toml` agent file.
#[must_use]
pub fn is_rejected_codex_agent_filename(file_name: &str) -> bool {
    !file_name.ends_with(&format!(".{CODEX_AGENT_EXTENSION}"))
}

/// Escape `s` for a TOML basic string (the `"…"` single-line form).
fn escape_toml_basic(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 || c as u32 == 0x7f => {
                let _ = write!(out, "\\u{:04X}", c as u32);
            }
            c => out.push(c),
        }
    }
    out
}

/// Escape `s` for a TOML multi-line basic string (the `"""…"""` form).
///
/// Every `"` is escaped rather than only runs of three, which keeps the
/// encoder from having to reason about where a run lands relative to the
/// closing delimiter — a `"""` sequence adjacent to the terminator would
/// otherwise end the string early.
fn escape_toml_multiline(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\r' => out.push_str("\\r"),
            '\n' | '\t' => out.push(ch),
            c if (c as u32) < 0x20 || c as u32 == 0x7f => {
                let _ = write!(out, "\\u{:04X}", c as u32);
            }
            c => out.push(c),
        }
    }
    out
}

/// Render a [`CodexAgent`] as the bytes of a standalone `.codex/agents/*.toml`
/// file, emitting [`CODEX_EMITTED_FIELDS`] in order.
#[must_use]
pub fn encode_codex_agent(agent: &CodexAgent) -> String {
    let mut out = String::new();
    for field in CODEX_EMITTED_FIELDS {
        match *field {
            "name" => {
                let _ = writeln!(out, "name = \"{}\"", escape_toml_basic(&agent.name));
            }
            "description" => {
                let _ = writeln!(
                    out,
                    "description = \"{}\"",
                    escape_toml_basic(&agent.description)
                );
            }
            "developer_instructions" => {
                let _ = writeln!(
                    out,
                    "developer_instructions = \"\"\"\n{}\"\"\"",
                    escape_toml_multiline(&agent.developer_instructions)
                );
            }
            _ => {}
        }
    }
    out
}

/// Render a Claude agent file as Codex-format bytes without writing to disk.
///
/// `claude_dir`/`mirror_dir` rebase relative links in the body exactly as
/// [`convert_codex_agent`] would.
///
/// # Errors
///
/// Returns an error string if the file cannot be read or its frontmatter
/// cannot be extracted or parsed.
pub fn render_codex_agent_bytes(
    input_path: &Path,
    agent_name: &str,
    claude_dir: &Path,
    mirror_dir: &Path,
) -> Result<Vec<u8>, String> {
    let (_agent, output, _warnings) =
        convert_codex_agent_inner(input_path, agent_name, claude_dir, mirror_dir)?;
    Ok(output)
}

/// Convert a single Claude agent file to Codex format and write it to
/// `output_path`.
///
/// # Errors
///
/// Returns an error string if the file cannot be read, parsed, or written.
pub fn convert_codex_agent(
    input_path: &Path,
    output_path: &Path,
    agent_name: &str,
    claude_dir: &Path,
    dry_run: bool,
) -> Result<(EmittedCodexAgent, Vec<ConversionWarning>), String> {
    let mirror_dir = output_path.parent().unwrap_or(output_path);
    let (agent, output, warnings) =
        convert_codex_agent_inner(input_path, agent_name, claude_dir, mirror_dir)?;

    if !dry_run {
        if let Some(parent) = output_path.parent() {
            fs::create_dir_all(parent)
                .map_err(|e| format!("failed to create output directory: {e}"))?;
        }
        fs::write(output_path, &output).map_err(|e| format!("failed to write file: {e}"))?;
    }
    Ok((
        EmittedCodexAgent {
            name: agent.name,
            description: agent.description,
        },
        warnings,
    ))
}

/// Shared body of [`render_codex_agent_bytes`] and [`convert_codex_agent`].
fn convert_codex_agent_inner(
    input_path: &Path,
    agent_name: &str,
    claude_dir: &Path,
    mirror_dir: &Path,
) -> Result<(CodexAgent, Vec<u8>, Vec<ConversionWarning>), String> {
    let content = fs::read(input_path).map_err(|e| format!("failed to read file: {e}"))?;
    let (frontmatter, body) =
        extract_frontmatter(&content).map_err(|e| format!("failed to extract frontmatter: {e}"))?;

    let frontmatter_str = String::from_utf8_lossy(&frontmatter).into_owned();
    let value: Value = serde_norway::from_str(&frontmatter_str)
        .map_err(|e| format!("failed to parse YAML: {e}"))?;
    let Value::Mapping(mapping) = value else {
        return Err("frontmatter is not a mapping".to_string());
    };

    let mut warnings: Vec<ConversionWarning> = Vec::new();
    let mut out = CodexAgent {
        // Identity comes from the `name` frontmatter key, resolved by the
        // shared discovery walk, never from the source subfolder.
        name: agent_name.to_string(),
        ..CodexAgent::default()
    };
    let dropped = walk_frontmatter_fields(&mapping, codex_field_policy(), |_action, key, v| {
        apply_preserve(&mut out, key, v);
    });
    warnings.extend(dropped.into_iter().map(|d| ConversionWarning {
        agent_name: agent_name.to_string(),
        field: d.field,
        reason: d.reason,
    }));

    let rebased_body = rebase_agent_links(&body, input_path, claude_dir, mirror_dir);
    out.developer_instructions = String::from_utf8_lossy(&rebased_body).into_owned();

    let encoded = encode_codex_agent(&out).into_bytes();
    Ok((out, encoded, warnings))
}

/// Copy a `Preserve`-tagged field value into the Codex output. `name` is
/// already resolved from the discovery walk, so the frontmatter copy is
/// ignored to keep one source of identity.
fn apply_preserve(out: &mut CodexAgent, key: &str, value: &Value) {
    if key == "description"
        && let Some(s) = value.as_str()
    {
        out.description = s.to_string();
    }
}

/// Convert every `.claude/agents/` agent into `.codex/agents/<name>.toml`.
///
/// # Errors
///
/// Returns an error if `.claude/agents/` cannot be read or two agents resolve
/// to the same `name`.
pub fn convert_all_codex_agents(
    repo_root: &Path,
    dry_run: bool,
) -> Result<CodexEmitResult, String> {
    let claude_dir = repo_root.join(".claude").join("agents");
    let codex_dir = repo_root.join(CODEX_AGENT_DIR);

    let sources = discover_agent_sources(&claude_dir)?;

    let mut out = CodexEmitResult::default();
    for (input, name) in sources {
        let filename = format!("{name}.{CODEX_AGENT_EXTENSION}");
        let output = codex_dir.join(&filename);
        if let Ok((agent, warnings)) =
            convert_codex_agent(&input, &output, &name, &claude_dir, dry_run)
        {
            out.result.converted += 1;
            out.result.warnings.extend(warnings);
            out.agents.push(agent);
        } else {
            out.result.failed += 1;
            out.result.failed_files.push(filename);
        }
    }

    Ok(out)
}

/// Resolve the agents the emitter would write, without writing anything.
///
/// Shares [`convert_codex_agent_inner`] with the emit path so the validator
/// and the emitter can never disagree about a description — a second,
/// hand-rolled frontmatter reader would drift the moment a description is
/// quoted or carries a colon.
///
/// # Errors
///
/// Returns an error if `.claude/agents/` cannot be read or two agents resolve
/// to the same `name`. An agent that fails to render is skipped, matching how
/// the emit path tallies it as failed rather than aborting.
pub fn plan_codex_agents(repo_root: &Path) -> Result<Vec<EmittedCodexAgent>, String> {
    let claude_dir = repo_root.join(".claude").join("agents");
    let mirror_dir = repo_root.join(CODEX_AGENT_DIR);

    let mut agents = Vec::new();
    for (input, name) in discover_agent_sources(&claude_dir)? {
        if let Ok((agent, _bytes, _warnings)) =
            convert_codex_agent_inner(&input, &name, &claude_dir, &mirror_dir)
        {
            agents.push(EmittedCodexAgent {
                name: agent.name,
                description: agent.description,
            });
        }
    }
    Ok(agents)
}

/// Render the generated region of [`CODEX_CONFIG_FILE`]: one `[agents.<name>]`
/// table per emitted agent, between the two markers. The returned text carries
/// no trailing newline — [`rewrite_generated_region`] owns the surrounding
/// whitespace so a rewrite is byte-stable.
#[must_use]
pub fn render_generated_region(agents: &[EmittedCodexAgent]) -> String {
    let mut out = String::from(GENERATED_REGION_START);
    for agent in agents {
        let _ = write!(
            out,
            "\n\n[agents.{}]\ndescription = \"{}\"\nconfig_file = \"agents/{}.{CODEX_AGENT_EXTENSION}\"",
            agent.name,
            escape_toml_basic(&agent.description),
            agent.name,
        );
    }
    out.push('\n');
    out.push_str(GENERATED_REGION_END);
    out
}

/// Replace the generated region of `existing` with `region`, or append it when
/// no region is present yet.
///
/// **Marker-first**: the already-present [`GENERATED_REGION_END`] marker is
/// searched for BEFORE the append anchor. Checking the anchor first would match
/// on every run and append a duplicate region each time — the re-runnable
/// substitution hazard this repository has hit before.
#[must_use]
pub fn rewrite_generated_region(existing: &str, region: &str) -> String {
    if let Some(end_at) = existing.find(GENERATED_REGION_END) {
        let start_at = existing.find(GENERATED_REGION_START).unwrap_or(end_at);
        let head = &existing[..start_at];
        let tail = &existing[end_at + GENERATED_REGION_END.len()..];
        return format!("{head}{region}{tail}");
    }

    let mut out = existing.to_string();
    if out.is_empty() {
        out.push_str(region);
        out.push('\n');
        return out;
    }
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out.push('\n');
    out.push_str(region);
    out.push('\n');
    out
}

/// Emit every Codex binding: the standalone agent files and the generated
/// region of `.codex/config.toml`.
///
/// # Errors
///
/// Returns an error if `.claude/agents/` cannot be read, if two agents resolve
/// to the same `name`, or if the config file cannot be read or written.
pub fn emit_codex_bindings(repo_root: &Path, dry_run: bool) -> Result<CodexEmitResult, String> {
    let emitted = convert_all_codex_agents(repo_root, dry_run)?;

    if !dry_run {
        let config_path = repo_root.join(CODEX_CONFIG_FILE);
        let existing = match fs::read_to_string(&config_path) {
            Ok(content) => content,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => String::new(),
            Err(e) => return Err(format!("failed to read {CODEX_CONFIG_FILE}: {e}")),
        };
        let updated =
            rewrite_generated_region(&existing, &render_generated_region(&emitted.agents));
        if updated != existing {
            if let Some(parent) = config_path.parent() {
                fs::create_dir_all(parent)
                    .map_err(|e| format!("failed to create {CODEX_CONFIG_FILE} directory: {e}"))?;
            }
            fs::write(&config_path, updated)
                .map_err(|e| format!("failed to write {CODEX_CONFIG_FILE}: {e}"))?;
        }
    }

    Ok(emitted)
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::panic)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn write(path: &Path, content: &str) {
        if let Some(p) = path.parent() {
            fs::create_dir_all(p).unwrap();
        }
        fs::write(path, content).unwrap();
    }

    #[test]
    fn rejected_codex_agent_filename_discriminates_on_extension() {
        assert!(!is_rejected_codex_agent_filename("probe-maker.toml"));
        assert!(is_rejected_codex_agent_filename("probe-maker.md"));
        assert!(is_rejected_codex_agent_filename("README"));
    }

    #[test]
    fn encode_emits_the_three_required_keys_in_order() {
        let encoded = encode_codex_agent(&CodexAgent {
            name: "probe".to_string(),
            description: "A probe.".to_string(),
            developer_instructions: "# Body\n".to_string(),
        });
        let name_at = encoded.find("name = ").unwrap();
        let desc_at = encoded.find("description = ").unwrap();
        let instr_at = encoded.find("developer_instructions = ").unwrap();
        assert!(name_at < desc_at && desc_at < instr_at, "got:\n{encoded}");
    }

    #[test]
    fn encode_omits_model_and_every_other_optional_key() {
        let encoded = encode_codex_agent(&CodexAgent {
            name: "probe".to_string(),
            description: "A probe.".to_string(),
            developer_instructions: String::new(),
        });
        for absent in [
            "model = ",
            "model_reasoning_effort = ",
            "sandbox_mode = ",
            "mcp_servers",
        ] {
            assert!(!encoded.contains(absent), "{absent} leaked:\n{encoded}");
        }
    }

    #[test]
    fn escape_toml_basic_escapes_quotes_and_backslashes() {
        assert_eq!(escape_toml_basic(r#"a"b\c"#), r#"a\"b\\c"#);
        assert_eq!(escape_toml_basic("a\nb"), "a\\nb");
    }

    #[test]
    fn escape_toml_multiline_keeps_newlines_but_escapes_quotes() {
        assert_eq!(escape_toml_multiline("a\nb"), "a\nb");
        assert_eq!(escape_toml_multiline("\"\"\""), "\\\"\\\"\\\"");
    }

    #[test]
    fn convert_all_writes_one_flat_toml_per_agent() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        write(
            &root.join(".claude/agents/role-a/first.md"),
            "---\nname: first-maker\ndescription: First.\nmodel: opus\n---\n# First\n",
        );
        write(
            &root.join(".claude/agents/second.md"),
            "---\nname: second-maker\ndescription: Second.\n---\n# Second\n",
        );

        let emitted = convert_all_codex_agents(root, false).unwrap();
        assert_eq!(emitted.result.converted, 2);
        assert_eq!(emitted.result.failed, 0);

        let first = fs::read_to_string(root.join(".codex/agents/first-maker.toml")).unwrap();
        assert!(first.contains("name = \"first-maker\""), "got:\n{first}");
        assert!(first.contains("description = \"First.\""), "got:\n{first}");
        assert!(first.contains("# First"), "got:\n{first}");
        assert!(!first.contains("model = "), "got:\n{first}");
        assert!(root.join(".codex/agents/second-maker.toml").is_file());
    }

    #[test]
    fn convert_all_warns_on_the_dropped_model_field() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        write(
            &root.join(".claude/agents/only.md"),
            "---\nname: only-maker\ndescription: Only.\nmodel: opus\ncolor: blue\n---\nBody\n",
        );
        let emitted = convert_all_codex_agents(root, false).unwrap();
        let fields: Vec<&str> = emitted
            .result
            .warnings
            .iter()
            .map(|w| w.field.as_str())
            .collect();
        assert!(fields.contains(&"model"), "got {fields:?}");
        assert!(fields.contains(&"color"), "got {fields:?}");
    }

    #[test]
    fn dry_run_writes_nothing() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        write(
            &root.join(".claude/agents/only.md"),
            "---\nname: only-maker\ndescription: Only.\n---\nBody\n",
        );
        let emitted = convert_all_codex_agents(root, true).unwrap();
        assert_eq!(emitted.result.converted, 1);
        assert!(!root.join(".codex/agents/only-maker.toml").exists());
    }

    #[test]
    fn render_bytes_matches_what_convert_writes() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        let src = root.join(".claude/agents/only.md");
        write(
            &src,
            "---\nname: only-maker\ndescription: Only.\n---\nBody\n",
        );
        convert_all_codex_agents(root, false).unwrap();
        let written = fs::read(root.join(".codex/agents/only-maker.toml")).unwrap();
        let rendered = render_codex_agent_bytes(
            &src,
            "only-maker",
            &root.join(".claude/agents"),
            &root.join(CODEX_AGENT_DIR),
        )
        .unwrap();
        assert_eq!(written, rendered);
    }

    fn fixture_agents() -> Vec<EmittedCodexAgent> {
        vec![EmittedCodexAgent {
            name: "probe-maker".to_string(),
            description: "A probe.".to_string(),
        }]
    }

    #[test]
    fn region_declares_one_table_per_agent_pointing_at_its_file() {
        let region = render_generated_region(&fixture_agents());
        assert!(region.starts_with(GENERATED_REGION_START), "got:\n{region}");
        assert!(region.ends_with(GENERATED_REGION_END), "got:\n{region}");
        assert!(region.contains("[agents.probe-maker]"), "got:\n{region}");
        assert!(
            region.contains("config_file = \"agents/probe-maker.toml\""),
            "got:\n{region}"
        );
    }

    #[test]
    fn rewrite_appends_a_region_when_none_is_present() {
        let existing = "[features]\nmulti_agent = true\n";
        let out = rewrite_generated_region(existing, &render_generated_region(&fixture_agents()));
        assert!(out.starts_with(existing), "prologue must survive:\n{out}");
        assert_eq!(out.matches(GENERATED_REGION_START).count(), 1);
        assert_eq!(out.matches(GENERATED_REGION_END).count(), 1);
    }

    #[test]
    fn rewrite_is_idempotent_and_never_duplicates_the_region() {
        let region = render_generated_region(&fixture_agents());
        let once = rewrite_generated_region("[features]\nmulti_agent = true\n", &region);
        let twice = rewrite_generated_region(&once, &region);
        let thrice = rewrite_generated_region(&twice, &region);
        assert_eq!(once, twice, "second pass must be a no-op");
        assert_eq!(twice, thrice, "third pass must be a no-op");
        assert_eq!(
            thrice.matches(GENERATED_REGION_START).count(),
            1,
            "an anchor-first rewriter would append a duplicate region here:\n{thrice}"
        );
    }

    #[test]
    fn rewrite_replaces_a_stale_region_and_preserves_both_sides() {
        let region = render_generated_region(&fixture_agents());
        let seeded = rewrite_generated_region("[features]\nmulti_agent = true\n", &region);
        let seeded = format!("{seeded}\n[agents.hand-maintained]\nconfig_file = \"x.toml\"\n");

        let next = render_generated_region(&[EmittedCodexAgent {
            name: "renamed-maker".to_string(),
            description: "Renamed.".to_string(),
        }]);
        let out = rewrite_generated_region(&seeded, &next);

        assert!(out.contains("[agents.renamed-maker]"), "got:\n{out}");
        assert!(
            !out.contains("[agents.probe-maker]"),
            "stale table survived:\n{out}"
        );
        assert!(out.contains("[features]"), "prologue lost:\n{out}");
        assert!(
            out.contains("[agents.hand-maintained]"),
            "content after the region lost:\n{out}"
        );
    }

    #[test]
    fn emit_writes_both_the_agent_files_and_the_config_region() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        write(
            &root.join(".claude/agents/only.md"),
            "---\nname: only-maker\ndescription: Only.\n---\nBody\n",
        );
        write(
            &root.join(CODEX_CONFIG_FILE),
            "[features]\nmulti_agent = true\n",
        );

        emit_codex_bindings(root, false).unwrap();
        let config = fs::read_to_string(root.join(CODEX_CONFIG_FILE)).unwrap();
        assert!(config.contains("[agents.only-maker]"), "got:\n{config}");
        assert!(config.contains("[features]"), "got:\n{config}");
        assert!(root.join(".codex/agents/only-maker.toml").is_file());
    }

    #[test]
    fn emit_dry_run_leaves_the_config_untouched() {
        let dir = tempdir().unwrap();
        let root = dir.path();
        write(
            &root.join(".claude/agents/only.md"),
            "---\nname: only-maker\ndescription: Only.\n---\nBody\n",
        );
        let before = "[features]\nmulti_agent = true\n";
        write(&root.join(CODEX_CONFIG_FILE), before);

        emit_codex_bindings(root, true).unwrap();
        assert_eq!(
            fs::read_to_string(root.join(CODEX_CONFIG_FILE)).unwrap(),
            before
        );
    }

    #[test]
    fn missing_claude_dir_is_an_error() {
        let dir = tempdir().unwrap();
        assert!(convert_all_codex_agents(dir.path(), false).is_err());
    }
}
