# pyright: strict
"""Example 53: A Data Migration With a REAL downgrade() -- Split, Then Merge Back."""

from __future__ import annotations

import contextlib  # => co-21: swallows alembic's own non-deterministic scaffolding chatter, same reason as Example 48
import io  # => the throwaway buffer redirect_stdout writes that chatter INTO
import os  # => reads connection settings, and builds/removes the scratch project directory
import shutil  # => co-21: cleanup -- removes the scaffolded project directory once this example is done
import tempfile  # => co-21: a fresh, self-contained directory for the scaffolded migration project

from alembic import command  # => co-21: init/revision/upgrade/downgrade -- the same API the alembic CLI itself calls
from alembic.config import Config  # => co-21: every alembic.command function needs one of these as its first argument
from sqlalchemy import create_engine, text  # => co-21: reads the ACTUAL row values back at each stage of the round trip

SQLA_URL: str = os.environ.get(  # => the SQLAlchemy dialect+driver URL, distinct from a plain DB-API DSN
    "SQLA_URL", "postgresql+psycopg://postgres:postgres@localhost:5432/orm_by_example"
)  # => override SQLA_URL in the environment to point at a different Postgres instance

ENV_PY = (  # => co-21: the SAME minimal env.py pattern from Examples 49-50 -- built as separate, individually-commented lines
    "from alembic import context\n"  # => co-21: `context` is alembic's OWN migration-runtime handle
    "from sqlalchemy import engine_from_config, pool\n\n"  # => co-21: builds a real Engine straight from alembic.ini's own section
    "config = context.config\n"  # => co-21: the SAME Config object bootstrap() constructed, now read back inside env.py
    'target_metadata = config.attributes.get("target_metadata")\n\n\n'  # => None -- this migration is hand-written, not autogenerated
    "def run_migrations_online() -> None:\n"  # => co-21: THE function alembic's runtime calls for a live-connection migration
    "    connectable = engine_from_config(\n"  # => co-21: reads the sqlalchemy.* keys straight out of alembic.ini's own section
    '        config.get_section(config.config_ini_section, {}), prefix="sqlalchemy.", poolclass=pool.NullPool\n'  # => no reuse needed
    "    )\n"  # => a short-lived migration run has no reason to KEEP a pooled connection open afterward
    "    with connectable.connect() as connection:\n"  # => borrows ONE connection for the whole migration run
    "        context.configure(connection=connection, target_metadata=target_metadata)\n"  # => co-21: binds THIS run's connection
    "        with context.begin_transaction():\n"  # => co-21: wraps every upgrade()/downgrade() call in ONE transaction
    "            context.run_migrations()\n\n\n"  # => the actual dispatch -- calls upgrade()/downgrade() on the revision below
    "run_migrations_online()\n"  # => co-21: executed the MOMENT alembic imports this file -- no __main__ guard, by design
)


def bootstrap(url: str, project_dir: str) -> Config:  # => co-21: init + env.py rewrite, shared setup for every Alembic example
    script_dir = os.path.join(project_dir, "migrations")  # => alembic's convention -- a "migrations" subfolder
    cfg = Config(os.path.join(project_dir, "alembic.ini"))  # => co-21: the Config object every command function needs
    cfg.set_main_option("script_location", script_dir)  # => tells Config where the scaffolded files live
    cfg.set_main_option("sqlalchemy.url", url)  # => co-21: the ONE connection string every migration runs against
    with contextlib.redirect_stdout(io.StringIO()):  # => swallows "Creating directory ... done" -- path varies per run
        command.init(cfg, script_dir)  # => co-21: scaffolds env.py, script.py.mako, README, versions/ (Example 48)
    with open(os.path.join(script_dir, "env.py"), "w") as f:  # => co-21: OVERWRITES the scaffolded env.py with our own
        f.write(ENV_PY)  # => a hand-edit step, exactly like a real project's post-init setup
    return cfg  # => ready for command.revision()/upgrade()/downgrade() calls


if __name__ == "__main__":  # => module entry point -- only runs when executed directly, not on import
    engine = create_engine(SQLA_URL)  # => an ORM-capable engine, used to seed data AND verify each stage of the round trip
    with engine.begin() as conn:  # => begin(): auto-commits on a clean exit, auto-rolls-back on an exception
        conn.execute(text("DROP SCHEMA public CASCADE"))  # => wipes EVERY table -- fully isolated from other examples
        conn.execute(text("CREATE SCHEMA public"))  # => a blank public schema, about to get the PRE-split table
        conn.execute(text("CREATE TABLE person (id SERIAL PRIMARY KEY, full_name TEXT NOT NULL)"))  # => co-21: the OLD shape
        conn.execute(text("INSERT INTO person (full_name) VALUES ('Ada Lovelace')"))  # => co-21: real data the round trip preserves

    project_dir = tempfile.mkdtemp(prefix="alembic_ex53_")  # => a fresh, throwaway migration project for this example
    # => co-21: contrast this with Example 54 -- SOME data migrations genuinely cannot be undone, and must say so
    cfg = bootstrap(SQLA_URL, project_dir)  # => scaffolds + rewires env.py, matching the earlier Alembic examples' setup

    with contextlib.redirect_stdout(io.StringIO()):  # => swallows "Generating .../0001_split_full_name.py ... done"
        rev = command.revision(cfg, message="split full_name", rev_id="0001")  # => co-21: an EMPTY skeleton, filled in below
    assert rev is not None and not isinstance(rev, list)  # => narrows the Union return type for pyright --strict below
    with open(rev.path, "w") as f:  # => co-21: a data migration -- SCHEMA change AND row-value transformation, both ways
        f.write(  # => upgrade() splits full_name; downgrade() merges first_name/last_name BACK into full_name
            '"""split full_name into first_name and last_name"""\n'  # => the migration's own docstring
            "from typing import Sequence, Union\n"  # => typed to match what command.revision()'s own skeleton generates
            "from alembic import op\n"  # => co-21: `op.add_column`/`op.drop_column` -- schema edits
            "import sqlalchemy as sa\n\n"  # => column TYPES for the new first_name/last_name columns
            'revision: str = "0001"\n'  # => co-21: THIS revision's own id -- matches the rev_id passed to command.revision()
            "down_revision: Union[str, Sequence[str], None] = None\n"  # => None -- the first revision in this project
            "branch_labels: Union[str, Sequence[str], None] = None\n"  # => unused here -- relevant only for branching histories
            "depends_on: Union[str, Sequence[str], None] = None\n\n"  # => unused here -- cross-branch dependency declarations
            "def upgrade() -> None:\n"  # => co-21: FORWARD -- split full_name into two columns, then drop full_name
            '    op.add_column("person", sa.Column("first_name", sa.String, nullable=True))\n'  # => co-21: nullable UNTIL backfilled
            '    op.add_column("person", sa.Column("last_name", sa.String, nullable=True))\n'  # => co-21: same -- populated next
            # => nullable=True on BOTH new columns is deliberate -- existing rows briefly have NULLs until the UPDATE below runs
            "    conn = op.get_bind()\n"  # => co-21: op.get_bind() -- the LIVE connection this migration runs on, for row-level SQL
            "    conn.execute(sa.text(\"UPDATE person SET first_name = split_part(full_name, ' ', 1), "
            "last_name = split_part(full_name, ' ', 2)\"))\n"  # => co-21: THE actual data transformation, one UPDATE
            '    op.alter_column("person", "first_name", nullable=False)\n'  # => co-21: NOW safe to require -- every row is backfilled
            '    op.alter_column("person", "last_name", nullable=False)\n'  # => same tightening for last_name
            '    op.drop_column("person", "full_name")\n\n'  # => co-21: the OLD column is gone -- upgrade() is now complete
            "def downgrade() -> None:\n"  # => co-21: REVERSE -- rebuild full_name from first_name + last_name, then drop both
            '    op.add_column("person", sa.Column("full_name", sa.String, nullable=True))\n'  # => nullable UNTIL backfilled
            # => the SAME add-then-backfill-then-tighten shape as upgrade() above, just mirrored for the opposite direction
            "    conn = op.get_bind()\n"  # => co-21: the same live-connection escape hatch, used in reverse
            "    conn.execute(sa.text(\"UPDATE person SET full_name = first_name || ' ' || last_name\"))\n"  # => co-21: MERGES back
            '    op.alter_column("person", "full_name", nullable=False)\n'  # => tightens once every row is backfilled
            '    op.drop_column("person", "first_name")\n'  # => co-21: removes the split columns -- back to the ORIGINAL shape
            '    op.drop_column("person", "last_name")\n'  # => the round trip is now complete, symmetrically
        )

    with contextlib.redirect_stdout(io.StringIO()):  # => swallows alembic's own noisy status lines
        command.upgrade(cfg, "head")  # => co-21: STEP 1 -- runs the split
    with engine.begin() as conn:  # => a fresh connection to verify the SPLIT state
        first, last = conn.execute(text("SELECT first_name, last_name FROM person")).one()  # => reads the two new columns
    print(f"after upgrade: first={first!r} last={last!r}")  # => Output: after upgrade: first='Ada' last='Lovelace'
    assert (first, last) == ("Ada", "Lovelace")  # => co-21: the UPDATE correctly split the original 'Ada Lovelace'

    with contextlib.redirect_stdout(io.StringIO()):  # => swallows alembic's own noisy status lines
        command.downgrade(cfg, "base")  # => co-21: STEP 2 -- runs the merge, undoing the split
    with engine.begin() as conn:  # => a fresh connection to verify the MERGED-back state
        (full_name,) = conn.execute(text("SELECT full_name FROM person")).one()  # => reads the restored single column
    print(f"after downgrade: full_name={full_name!r}")  # => Output: after downgrade: full_name='Ada Lovelace'
    assert full_name == "Ada Lovelace"  # => co-21: the EXACT original value survived a full split-then-merge round trip
    # => a naive downgrade that just DROPPED first_name/last_name without merging them back would have lost this row's data entirely
    # => co-21: this is what "reversible" means for a DATA migration, not just a schema one -- downgrade() must undo
    # => both the STRUCTURE change and the VALUE transformation, or a rollback silently corrupts real user data

    shutil.rmtree(project_dir)  # => cleanup -- this example's own throwaway project, not a real repository
    print("ex-53 OK")  # => Output: ex-53 OK
