// Example 5: Hydration Attaches React to Server HTML. (co-05)
//
// Hydration: the server already sent fully-formed HTML (Example 2); hydrateRoot ATTACHES React's
// event handling to that existing HTML instead of re-rendering it from scratch. After hydration,
// the same DOM nodes become interactive.
//
// > **Accuracy note**: "`hydrateRoot` lets you display React components inside a browser DOM node
// > whose HTML content was previously generated by `react-dom/server`."
// > Source: react.dev, hydrateRoot (https://react.dev/reference/react-dom/client/hydrateRoot).

// The server's pre-rendered HTML already has the button in the DOM.
const serverHtml = `<button id="b">count: 0</button>`; // => exists before hydration
// => a user could already READ this; they just cannot CLICK it to update until hydration attaches the handler

// A minimal in-memory DOM node with an attachable click handler.
interface DomEl {
  // => enough of a DOM node to model "attach a handler to existing markup"
  html: string; // => the markup the server sent
  handler: (() => void) | null; // => null = not yet interactive (pre-hydration)
}

const button: DomEl = { html: serverHtml, handler: null }; // => pre-hydration: handler is null
// => handler === null means clicks do nothing yet -- the DOM is present but inert

// hydrateRoot attaches the event handlers to the EXISTING server HTML (no re-render).
function hydrateRoot(el: DomEl, onEvent: () => void): void {
  // => co-05: attach, do not recreate -- the server's <button> is reused
  el.handler = onEvent; // => now the same node is interactive
}

let count = 0; // => the component state
// => the click handler updates state and (in a real app) re-renders; here it mutates count

console.log("pre-hydration:", button.html, "| interactive:", button.handler !== null); // => BEFORE attach: interactive is false
hydrateRoot(button, () => {
  // => this closure is the React click handler, now wired to the existing button
  count += 1; // => a click increments the count
  button.html = `<button id="b">count: ${count}</button>`; // => reflect the new state in the DOM
});

button.handler!(); // => simulate a user click AFTER hydration
button.handler!(); // => a second click
console.log("post-hydration:", button.html); // => Output: post-hydration: <button id="b">count: 2</button>
